### ISSUE TITLE
Cover photo, image detected wrong size

### ISSUE THREAD

**Issue by IAmTheWebb** [scubajeff/lespas#101]
Hi, excellent app!
I spotted that some of my older folders have pixelated cover images, if I select another image to set as the cover it'll change but still only shows a pixelated top corner of the image.
It looks like lespas thinks these images are considerably lower resolution than they are, 160 x120 instead of 4310x2868.

![Screenshot_20230106-060137_Les_Pas](https://user-images.githubusercontent.com/17071553/210955452-293bba7b-b7d1-4abb-b625-67013fafc9ba.png)

Nextcloud shows
![IMG_20230106_074818](https://user-images.githubusercontent.com/17071553/210967609-135e23e6-7bd5-426e-b665-5b5cc590bdaf.jpg)

Let me know if you need any further details. Example problematic image below..
![DSC_0673](https://user-images.githubusercontent.com/17071553/211014041-273c2a1d-74db-42fa-b050-67ded71be015.jpg)

**Comment by scubajeff** [comment]
Bug confirmed.

**Comment by scubajeff** [comment]
Android's ExifInterface API is used to read photo file's EXIF, in this case, it reports wrong dimension data and can't read photo taken date neither. Since this is AOSP, nothing I can do despite reporting this bug to Google.

**Comment by scubajeff** [comment]
Google engineer just [confirmed](https://issuetracker.google.com/issues/264729367) that it's a bug in ExifInterface library. Though not sure when they will release the fix.

**Comment by scubajeff** [comment]
bug fixed upstream.
