### ISSUE TITLE
How indexing new folder?

### ISSUE THREAD

**Issue by rockrob** [scubajeff/lespas#103]
Hi all,
sometimes I need create new folders from nextcloud files without passing the app,
but lespas app don't see these folders .
There is a procedure to indexing new folders?

**Comment by scubajeff** [comment]
Create new folder under lespas/ folder, then copy photos into it. Or symlink your existing folder under lespas/

**Comment by rockrob** [comment]
> Create new folder under lespas/ folder, then copy photos into it. Or symlink your existing folder under lespas/
This is the method that I use,but the folders aren't noto display into lespas app ..into these folders there aren't files *.json

> Create new folder under lespas/ folder, then copy photos into it. Or symlink your existing folder under lespas/

**Comment by scubajeff** [comment]
Did you put any picture files in the newly created folder? Empty folder will not be synced.

You can also goto the setting screen, scoll down to Sync section, then click the Sync Status menu item and see the result of the last sync. You could also launch resync there.

**Comment by rockrob** [comment]
Could be subfolder problem?
I have sync mobile photos with nextcloud app and it create main folders "2022" and some sub folders (one per month):01. 02. 03 and so on

**Comment by rockrob** [comment]
Thank you @scubajeff 
The problem was nested directory..
