### ISSUE TITLE
Text search for Albums by name in app and import dialog

### ISSUE THREAD

**Issue by DeveloperOl** [scubajeff/lespas#104]
**Is your feature request related to a problem? Please describe.**
I have a lot of albums which have a global naming convention and I'm always frustrated when I have to scroll through all Folders to find the one I am looking for (In the app and when importing new Photos using the import dialog).

**Describe the solution you'd like**
It would be nice to have a text filter at the top of the app and dialog to filter the results.

**Describe alternatives you've considered**
I think I can implement this if you are willing to accept a pull.

**Additional context**
No additional context.

**Comment by scubajeff** [comment]
PR always welcomed

**Comment by frederikb96** [comment]
I am also interested in a basic search function for files or folders. Is there already some progress? :)

**Comment by scubajeff** [comment]
@frederikb96 Feature of searching by picture's name is always available. In single album view, choose 'Show name' in the menu, the list format will change and a search action will appear on the Toolbar.

**Comment by frederikb96** [comment]
Ah nice, I didn't know that. Then, I would only miss a feature to search for folders :)

**Comment by DeveloperOl** [comment]
I am wishing for the same feature, but didnt have time to look into that yet. If you have time, feel free to lat me know in this issue, otherwise i will work in it as soon as I have time :)

**Comment by marcus-k** [comment]
@DeveloperOl I'm curious if you have made any progress in this update? I was about to create a new issue about this exact feature before I saw this thread. It's the main missing feature from Les Pas at the moment that was forcing me to look for other alternatives. The folder structure was what was keeping me using Les Pas though so it has certainly been a challenge.

**Comment by DeveloperOl** [comment]
@marcus-k I totally agree with you.
Unfortunatly I have realized, that my experience with Android UX Design is not sufficient to understand how I can create a simple search bar in the android design tool...

**Comment by marcus-k** [comment]
@DeveloperOl No worries, I can't say I have much experience with it either so I'm not one to complain. Perhaps we just need to ask @scubajeff really nicely for its implementation one day :)

**Comment by scubajeff** [comment]
This is in my todo list. 

Adding name search in album list screen is pretty easy, considering it's almost the same as searching for name in photo list. The real difficulty here is how to do it properly for photo import dialog, it's a UX design issue though. What kind of UI element should be added to the already busy dialog to launch the soft keyboard? Any better idea than a search button?

**Comment by marcus-k** [comment]
For the album list screen search, yeah I think the implementation matching the photo list search makes sense. For the photo import popup dialog, it might be an idea for beside the "To Album:" text to have a TextBox that the user could tap and type in an album name. Then, the album list can get filtered based on the entered text. Alternatively, a search button right-aligned in that same space to display an input textbox might be neat too, something sort of similar to how the photo list search is implemented now.

Though I'm not sure what is in the realm of possibility in those popup dialogs. Just some ideas I had really.
