### ISSUE TITLE
Sync error: http code 400

### ISSUE THREAD

**Issue by TalOrenshtein** [scubajeff/lespas#106]
**Describe the bug**
Syncing got stuck while trying to sync DCIM, log says http response code 400.

**To Reproduce**
Try to sync? Sorry, I don't really know.

**Expected behavior**
File uploaded successfully, http code 204.

**Smartphone (please complete the following information):**
 - Device: Xiaomi mi 9T
 - OS: Android 11
 - Version [e.g. 22]: 2.7.3

**Additional context**
Log: (That's the only relevant part)
`192.168.0.2 - Tal [20/Feb/2023:16:50:10 +0000] "PUT /remote.php/dav/uploads/Tal/IMG_20210912_163106.jpeg HTTP/1.1" 400 664 "-" "LesPas_v2.7.3"
`

**Comment by scubajeff** [comment]
Is this file, 'IMG_20210912_163106.jpeg', larger than 50MB? Do you see a folder named 'IMG_20210912_163106.jpeg' in Nextcloud's data folder under '<DATA_FOLDER>/Tal/uploads/'?

**Comment by TalOrenshtein** [comment]
Thanks for the quick replay!

> Is this file, 'IMG_20210912_163106.jpeg', larger than 50MB? 

No.
> Do you see a folder named 'IMG_20210912_163106.jpeg' in Nextcloud's data folder under '<DATA_FOLDER>/Tal/uploads/'?

No
 >What's the version of your Nextcloud and the system?

Ubuntu server 22.0.4 (if I'm not mistaken, it might've update itself). At the nc system settings it says "Linux 5.15.0-60-generic x86_64" . nextcloud snap 25.0.3.

**Comment by scubajeff** [comment]
This is interesting. The log said Les Pas is uploading a file to `/remote.php/dav/uploads/Tal/`, which is a special folder reserved for chunked upload of large file to Nextcloud server. Les Pas might had some difficulty in estimating the file size. Could you send me the file `IMG_20210912_163106.jpeg` for further investigation? My email: scubajeffrey@protonmail.ch

**Comment by TalOrenshtein** [comment]
Tbh I copied it by hand because I couldn't copy from the actual log. Your comment makes me think I mixed up with two lines or something. Let me check it out and let you know.

**Comment by TalOrenshtein** [comment]
Yep, it's actually
`192.168.0.2 - Tal [20/Feb/2023:16:50:10 +0000] "PUT /remote.php/dav/files/Tal/Photos/IMG_20210912_163106.jpeg HTTP/1.1" 400 664 "-" "LesPas_v2.7.3" `

So sorry for the confusion above.

**Comment by scubajeff** [comment]
So when you first launched Les Pas, after logging in, you have the chance of choosing a parent folder to host Les Pas folder, did you choose `Photos`?

Is the mentioned file in one of your albums or in camera roll?

Are ther any other files that got uploaded successfully?

Please also have a look at 'Sync status' in Les Pas's Setting and tell me what you see there.

**Comment by TalOrenshtein** [comment]
> So when you first launched Les Pas, after logging in, you have the chance of choosing a parent folder to host Les Pas folder, did you choose `Photos`?
> 
> Is the `Photos` exist in your Nextcloud home folder? Do you see subfolder `lespas` and `DCIM` in `Photos`?
> 
> Is the file `IMG_20210912_163106.jpeg` in one of your albums or in camera roll?
> 
> Are there any other files that got uploaded successfully?
> 
> Please also have a look at 'Sync status' in Les Pas's Setting and tell me what you see there.

It has and I edited it once again  🤦‍♂️  did it from memory but now I've looked at the next cloud app to see the path, so I've filled it as I think it is.
I'm so sorry I've wasted your time. I'll have the access to the log this evening, please let me verify the path and comment here again.

**Comment by TalOrenshtein** [comment]
I'm so sorry I've wasted your time. I didn't fill it well.
 I'll have the access to the log this evening, please let me verify the path and comment here again.

 I only saw from the interface and  I do see the lespas folder inside the photo folder, and DCIM/name_of_device/Camera, and the photos are inside the Camera folder.

**Comment by TalOrenshtein** [comment]
For the last time:
`192.168.0.2 - - - [20/Feb/2023:16:50:10 +0000] "PUT /remote.php/dav/files/Tal/Photos/DCIM/xiaomi_mi%20t/Camera/IMG_220519_124109.jpg HTTP/1.1" 400 664 "-" "LesPas_v2.7.3"`
That's the path for sure this time.
And yes, I do have a Photos/lespas subfolder.
The sync status is stuck on that specific file.

**Comment by scubajeff** [comment]
Ok, the path seems right to me, except that the file name could be more like `IMG_`**`20`**`220519_124109.jpg`. Anyway, I guess you choosed 'Yes' when Les Pas ask if you want to backup all you existing camera roll during login process. And seems like there are quite some of them waiting in line. It takes time and Android OS will kill any background process which last longer than 30 minutes, although Les Pas will schedule another one later. So, let's do these:

1. Go to Setting -> Sync status, click Resync, see if backup still stuck on this same file
2. If it doesn't, then you are good and just need to give Les Pas some more time finishing the job
3. If it does, then there must be something special about this particular file. You might need to mail me the file for debugging
