### ISSUE TITLE
Feature: Specify name of shared_with_me folder in App settings

### ISSUE THREAD

**Issue by frederikb96** [scubajeff/lespas#108]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the possibility to use a different name and path for the `/shared_with_me` folder. This way one could specify a folder like `/Photos/shared_with_me`. And move all data that is not related to Photos simply away into other directories.

**Describe the solution you'd like**
If I see it correctly, the `shared_with_me` folder name and path is [hard-coded into the code here](https://github.com/scubajeff/lespas/blob/master/app/src/main/java/site/leos/apps/lespas/publication/NCShareViewModel.kt#L1745).

[Nextcloud does support other folder names and also other paths](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#sharing). I just tested to specify the name in the Nextcloud config as `/test-something/shared_with_me` and the folder will be automatically created if you get a share. So no problem with this from Nextclouds site.

Would it be possible to be able to specify the path and name in the App settings?

This has a second use case: If you do **not have access to the Nextcloud server config**, you can set it to **`Shared`** which is the **default for Nextcloud currently** or **`/`** which was previously the default.

**Comment by frederikb96** [comment]
Alternative:
1. Only make it settable once during the first launch of the app, like with the home folder
2. Only make it settable (for root users) via the Android `/data/data/site.leos.apps.lespas/shared_prefs/site.leos.apps.lespas_preferences.xml` file. There, the home folder is specified, or am I wrong?

**Comment by scubajeff** [comment]
Nextcloud treats share as a single image for the whole system, there is no way to differentiate from the API result which app shares which resource. That's also why shares receiving folder name can only be customized in the `config.php` file, and BTW no API provided to make this change too. You can change this setting as you wish, everything will be fine for all the shares published before the change. However, any shares done by any app after the change will goes under the new folder, user still can't tell which from which.

So you see, this limited customization of share receiving folder name is merely a good gesture from Nextcloud to prevent received items populating user's home folder.

The `share_with_me` in the http endpoint string is not a hard-coded name, instead a parameter setting asking that API call to return only the list of shares received by the user.

**Comment by frederikb96** [comment]
Thank you very much for the clarification :)

Just to make sure that I got it right:
It is not relevant for your app, which folder name I specify in the Nextcloud `config.php`, since your app also "finds" shares if they go to a folder named e.g. `/Shared`.

So, I would like to ask one follow-up question independent of the previous one:
When I receive a normal share from a friend with a folder containing pictures (via Nextcloud share function in Browser, **not** via Les Pas share function), how does your app know that this new folder should not be displayed in the Les Pas app.

Thanks again for your time and your help!

**Comment by scubajeff** [comment]
If my memory is right (it has been a while since Share/Publish feature of Les Pas turned stable), Nextcloud's API of `list shares` will return the shared item's original path name, Les Pas will look for `lespas` in that string, and double check that a JSON file can be located in it. That's what the 'peeking' is doing.

**Comment by frederikb96** [comment]
Ok makes sense, thanks!
