### ISSUE TITLE
Move image to different album from within the app

### ISSUE THREAD

**Issue by BettaGeorge** [scubajeff/lespas#11]
**Is your feature request related to a problem? Please describe.**
As far as I can tell, once you have added a picture to an album, it is stuck there forever. The only way to get it into a different album is to go to your PC, move it to a different folder in your Nextcloud, and wait six hours. That makes it essentially impossible to organize your gallery with lespas, because if you accidentally put a picture into the wrong album, you cannot get it back out (unless you delete it and import it anew).

**Describe the solution you'd like**
Add a "move" button to pictures to move them from the current folder to a different one. Preferably add the same button when you have multiple pictures selected to facilitate moving lots of pictures at the same time.

**Describe alternatives you've considered**
I tried just using the phone's file manager to move the pictures, but the app storage does not show up there.

My current workaround (for anyone coming across this) is to open the photo in lespas, tap on "share", share to lespas, which lets me _copy_ it to an album, and then delete the original photo. This works, but is needlessly complicated. It also does not work for multiple selected pictures, because sharing them _unselects_ them, which means you have to select everything a second time in order to delete it.

**Related feature: Move from Camera Roll**
The camera roll has the same problem: I can add photos to albums via the little Les Pas icon, but this does not delete them from my DCIM folder. Consequently my DCIM folder is cluttered with duplicates of stuff I have long since organized via Les Pas. Here I would like the same option: rather than copy the image to Les Pas, move it there so I do not have to delete it manually.

**Comment by scubajeff** [comment]
I myself has more than a few photos which need to be presented in different albums. I use the reshare way you mentioned to do it. But you are right, a Move function is more straight forward. Would try to implement this in next release.

**Comment by BettaGeorge** [comment]
After figuring out that I can use the "camera roll" to organize my newly taken pictures into Les Pas, I have updated the original feature request with a new paragraph – the camera roll currently has the same problem where I have to go back and manually delete photos I wish to move.

**Comment by scubajeff** [comment]
Instead of clustering the action menu bar, I have this, choose copy or move action in adding media dialog:
![Screenshot_1617845637](https://user-images.githubusercontent.com/458032/113955523-64e93780-980b-11eb-8278-62d87e202832.png)
