### ISSUE TITLE
Album date not updated after picture dates are updated

### ISSUE THREAD

**Issue by frederikb96** [scubajeff/lespas#110]
I have an album, which contained pictures, which had a "wrong" date. So I changed the date of the pictures on my PC. They synced to the server and I synced them to Les Pas. I check in the album in Les Pas, that the date of the pictures is correct now by clicking on the image and pressing the info button. All pictures have the correct date now and everything is synced. I press the sync button again, close the app, start the app again. However, the date of the album still shows the previous "wrong date" even though there is no picture in this album with this wrong date anymore.

Example: All pictures have the date 2022-06-05 but one picture had 2023-03-13. So I fixed the date of the 2023-03-13 picture, but the album still shows that the range is until 2023-03-13.

Expected behavior would be, that the album refreshes and shows that the album only contains pictures from 2022-06-05.

However, there is a solution to this problem:
Remove the folder/album from lespas folder on the server, and sync on the app and then add it again on the server and sync to the app. Now the correct date is shown.

**Comment by scubajeff** [comment]
Yes, this is a bug when you changed the very first and/or very last photo's date in an album, new start/end date is not reflected in album list. It's already fixed in a working branch which will introduced a new feature for re-scanning Exif for an album. There are still some final touches to be done before it can be merged and released.

**Comment by frederikb96** [comment]
Perfect, thank you very much!

**Comment by ahormann** [comment]
Does this bug also affect the sorting by date of the picture within an album or is this a new bug?

**Comment by scubajeff** [comment]
@ahormann It should not. Did you have any problem with sorting of photos or albums?

**Comment by scubajeff** [comment]
This bug is fixed in latest release 2.8.3
