### ISSUE TITLE
Camera Roll - in server-side backup directory photos visible even though deleted

### ISSUE THREAD

**Issue by frederikb96** [scubajeff/lespas#113]
**Describe the bug**
Naming:
backup directory = the directory on the server where the camera roll pictures are automatically getting backed up to

If I only have one photo in my camera roll (on phone and on server in Les Pas backup directory) and I delete the photo via Les Pas app in the backup directory, it gets deleted correctly on the server but is still visible in the app. Restart of the app, still shows the picture in the camera roll backup directory and if deleting again, it disappears only until a new restart of the app. Only solution to get rid of this "zombie" picture is to take another picture and wait until it is backed up. Then the "zombie" picture is not shown anymore in the Les Pas app in the backup tab and only the new picture is correctly visible again.

Moreover, since this zombie picture behavior happened to me, there is another strange behavior: I have the new Picture backup setting enabled. If I place a new photo in the Pictures folder on the phone, it gets backed up correctly to the server. However, it is not displayed in the Les Pas app in the backup folder tab. There are only the photos displayed, which were backed up from the camera folder on the phone. So, the only way to access those pictures is to manually move them via Nextcloud to the backup folder, where Les Pas uploads the camera photos.

**To Reproduce**
1. I have camera roll and Pictures backup enabled
2. I have a single photo in the camera folder on the phone
3. Starting Les Pas executes the camera backup and the single photo is now also on the server side
4. In the Les Pas app I look at the camera folder and the backup folder, I can see one image in both tabs, thats good
5. In the backup tab, I now delete the picture, it gets deleted from the server correctly but it is still showing up in Les Pas
6. I try to delete the picture again, but does not help
7. I quit the app, and open camera toll again
8. Deleting the local image on the phone works
9. But deleting the image in the backup tab of Les Pas, still does not work

I also send you a mail with the server log and a screen-record video attached, which might help to debug the problem, thanks :)

**Expected behavior**
The picture gets deleted from the server AND also is not shown anymore in Les Pas

**Smartphone (please complete the following information):**
- App version 2.8.0
- Device: FP4
- OS: /e/os 1.8
- Version: Android 12
- Nextcloud AIO docker Setup version 25.0.4

**Comment by scubajeff** [comment]
The archive only shows your camera roll backup, that's why it's in camera roll screen.

For ghost picture issue, I will look into it. Maybe it's another edge case.

Thank you for reporting.

**Comment by scubajeff** [comment]
Confirm this is a bug. To facilitate archive management on server, Les Pas has to use webdav PROPFIND call with infinite depth argument. This is **VERY**  time consuming. So Les Pas will save a local cache copy of the result. From the screen recording you sent me, seems like the cache has been successfully cleared when the last picture deleted, but the list is not updated accordingly.
