### ISSUE TITLE
Create new album option is hidden at the end of folder list in move/copy window

### ISSUE THREAD

**Issue by frederikb96** [scubajeff/lespas#114]
**Is your feature request related to a problem? Please describe.**
When being in the pop-up window to move/copy images to an album, the "create new album" is not the first entry. Consequently, I have to scroll to the end of the list of my hundred of folders before I can see this entry. Firs, I thought that there was not even the possibility to create a new album from this view. This might be misleading for new users.

Moreover, the thumbnail displayed next to the "create new album" text is showing some random picture from some of my albums. I wonder why? :)

In the screenshot, I scrolled all the way down:

![Screenshot_20230407-125112_Les Pas](https://user-images.githubusercontent.com/83548283/230598024-b0f0b2f8-6c74-484a-bbf3-2c7b9e843ef1.png)

**Describe the solution you'd like**
Show the create new album option always as the first entry instead of last entry in the list.

**Additional context**
I have my folders sorted by date descending.

**Comment by scubajeff** [comment]
Wrong picture shown in this dialog is a known bug for a very long time, sadly I still can't find the cause, the implementation of this list adapter is the same as in the other lists, but those lists do not experience this bug.

'New Album' item should be on the top, I believe more and more users prefer creating albums on the server.

**Comment by frederikb96** [comment]
Ah ok, yeah no problem, the wrong picture doesn't bother me :)

I am uncertain if I got your second part correctly. Do you mean that create new album is listed on top for you, and it must be an issue with my specific setup?

**Comment by scubajeff** [comment]
I mean placing it to the top of the list is a good idea. User will see it when they start with just a few albums, but obviously some will not if they created a lot of albums on server before the first sync.
