### ISSUE TITLE
Synchronization gets stuck at "synchronizing local changes" - error in log 409

### ISSUE THREAD

**Issue by frederikb96** [scubajeff/lespas#115]
**Describe the bug**
Now, my synchronization always gets stuck at "synchronizing local changes". Nothing is synchronizing anymore.

**To Reproduce**
Sadly, I do not know how to reproduce this issue. It just happened.

The last things, that I did before the error occurred:
- I added a bunch of new albums via server side to the lespas folder (they started to sync correctly, but at some point the error occurred and now they are not syncing anymore)
- I took some pictures, which should have been processed by the camera roll function
- A new person on my server, started to use the Les Pas app

**What I tried**
I tried everything from killing the app and starting it again to clearing the cache and disabling camera roll function and deleting all pictures in camera roll and archive.

However, I do not find a way to recover from this sync failure. If I create new albums, in the app it looks like they are created but nothing appears on the server, same for the camera roll.

The only option might be to remove the app completely and start from scratch again to get rid of the error again.

**Screenshots**

![Screenshot_20230408-193801_Les Pas](https://user-images.githubusercontent.com/83548283/230735815-51683bc2-1279-4412-911a-c79804991d49.png)

**Logs**

I recorded logs after killing the app and starting it again. I stopped recording after I checked in the sync state that the "syncing local changes" error occured again. One error in the log is this.

I also checked the complete log of the last hours and in the last 3 hours, the error with trying to delete the 909850.md occurred 130 times.

```
{
  "level": "error",
  "ts": 1680975458.7118106,
  "logger": "http.log.access.log1",
  "msg": "handled request",
  "request": {
    "remote_ip": "172.90.0.1",
    "remote_port": "59378",
    "proto": "HTTP/2.0",
    "method": "DELETE",
    "host": "cloud.bergrunde.net",
    "uri": "/remote.php/dav/files/Freddy/Pictures/lespas/.__picoblog__/content/909850.md",
    "headers": {
      "Authorization": [],
      "Content-Length": [
        "0"
      ],
      "Accept-Encoding": [
        "gzip"
      ],
      "User-Agent": [
        "LesPas_v2.8.0"
      ]
    },
    "tls": {
      "resumed": false,
      "version": 772,
      "cipher_suite": 4865,
      "proto": "h2",
      "server_name": "cloud.bergrunde.net"
    }
  },
  "user_id": "",
  "duration": 0.115946179,
  "size": 181,
  "status": 409,
  "resp_headers": {
    "Referrer-Policy": [
      "no-referrer"
    ],
    "X-Permitted-Cross-Domain-Policies": [
      "none"
    ],
    "Expires": [
      "Thu, 19 Nov 1981 08:52:00 GMT"
    ],
    "Alt-Svc": [
      "h3=\":443\"; ma=2592000"
    ],
    "Date": [
      "Sat, 08 Apr 2023 17:37:38 GMT"
    ],
    "Cache-Control": [
      "no-store, no-cache, must-revalidate"
    ],
    "Set-Cookie": [],
    "Content-Security-Policy": [
      "default-src 'none';"
    ],
    "Strict-Transport-Security": [
      "max-age=31536000;",
      "max-age=31536000;"
    ],
    "Pragma": [
      "no-cache"
    ],
    "Server": [
      "Caddy",
      "Caddy",
      "Apache/2.4.56 (Unix)"
    ],
    "X-Content-Type-Options": [
      "nosniff"
    ],
    "X-Frame-Options": [
      "SAMEORIGIN"
    ],
    "X-Powered-By": [
      "PHP/8.0.28"
    ],
    "X-Xss-Protection": [
      "1; mode=block"
    ],
    "X-Robots-Tag": [
      "noindex, nofollow"
    ],
    "Content-Type": [
      "application/xml; charset=utf-8"
    ]
  }
}
```
Smartphone (please complete the following information):
- App version 2.8.0
- Device: FP4
- OS: /e/os 1.8
- Version: Android 12
- Nextcloud AIO docker Setup version 25.0.4

**Comment by scubajeff** [comment]
Is this file `/Pictures/lespas/.__picoblog__/content/909850.md` existed on your server? Looks to me that this is the same issue like before caused by Caddy returns 409 instead of 404 when client request deleting a file which is not exist on server.

**Comment by frederikb96** [comment]
Thank you very much for the swift reply. The file is not existing on my server.

I investigated a little more, and I guess the picoblog file is related to the markdown web interface editor of Nextcloud. I remember that I accidentally created a Readme.md in the lespas folder.

**Comment by scubajeff** [comment]
That folder is for publishing your album as a photo blog to general public.

**Comment by frederikb96** [comment]
Ah ok thanks.

About the sync error: I did a clean install of the app and let it sync all my albums over the night. The sync error did not happen again so far. So for now it is all working again :)

**Comment by frederikb96** [comment]
Ok the error happened again. However, now I figured out a way to get rid of it without the need to reinstall the app.

I simply create the files:
```
.../lespas/.__picoblog__/content/909850.md
.../lespas/.__picoblog__/assets/909850
```

After starting the app again, it syncs again since it is not getting the error that the files do not exist. This seems to be a good workaround for me until it is fixed :)

**Comment by frederikb96** [comment]
Thank you very much for the new release with all the issues being fixed! :)
I can confirm that this one here is fixed as well now.

**Comment by scubajeff** [comment]
Thank you for spending time testing this.
