### ISSUE TITLE
New app available: Companion Nextcloud PHP App to automatically move shares to a different folder

### ISSUE THREAD

**Issue by frederikb96** [scubajeff/lespas#119]
Hi,

I wrote a [Nextcloud server side php app](https://gitlab.com/frederikb96/nextcloud-mvsharedpics), which can automatically move folders (albums), which contain e.g. pictures to a different customizable folder. This way, users do not have to manually move received shares (which contain pictures) to their `/Photos` or e.g. `/Photos/shared_with_me` folder. This is useful to keep your folders clean and organized. (Since Les Pas is using the share API, there are no issues with moving shared folders around as you like.)

I also added some additional tweaks, which can be enabled or disabled in the config of the app. I like to change all permissions from joint shares from 7 to 31 automatically (being able to delete files, and re-share). But these options can be disabled in the config.

I am currently using Les Pas and this app with my family to share and edit albums, and it is working fine.

I am also planing to publish the app in the Nextcloud app store. Furthermore, I will also work on a user interface, such that each user can individual specify where they want to move their shared albums to (right now this is a global configuration for all users).

I just wanted to let the users of Les Pas know that this app exists now, since there were some discussions about these kinds of topics in the past here. Maybe, it is somehow helpful to someone :)

**Comment by scubajeff** [comment]
Great!! Drop me a plain README file, and I will make a link to it in Les Pas's README.

**Comment by frederikb96** [comment]
Nice, sounds good :)


What do you mean by plain Readme? This here would be the link to the Project/Readme: https://gitlab.com/frederikb96/nextcloud-mvsharedpics

A quick summary would be:

The Nextcloud server app _Mv Shared Pics_ can be used to automatically move folders a user received via a share, which contain files with a specific mime type (e.g. pictures) to a configurable destination. This is useful in combination with albums shared via _Les Pas_ since they will be automatically moved to the desired location such that the default folder where shares are received is kept clean.

**Comment by scubajeff** [comment]
Les Pas's [FAQ](https://github.com/scubajeff/lespas#checklist-for-enabling-sharing-on-nextcloud-server) updated with link to your project. Thanks for your contribution.

**Comment by frederikb96** [comment]
Thanks!
