### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [scubajeff/lespas#121]
**Describe the bug**
`Unrecognized VM option 'MaxPermSize=2048m'`. This option is removed in jdk 17.

Do you know why it works for you? Maybe you ran the gradle host on a different jvm?

**Comment by linsui** [comment]
Insteresting. https://github.com/scubajeff/lespas/blob/master/app/build.gradle#L46 This line requires jdk 17 to build the apk. And gradle 8 also requires jdk 17.

**Comment by scubajeff** [comment]
My Ubuntu has OpenJDK 11 installed, but I think Android Studio is using it's embedded JBR which is JDK 17.0.6, I have no problem building app though. Are you with F-Droid team? Is this a message telling me that F-Droid is having trouble building this app?

**Comment by linsui** [comment]
Yes, `MaxPermSize=2048m` makes the build fail. I can patch it out but I thought it's better if you can remove it.

> My Ubuntu has OpenJDK 11 installed, but I think Android Studio is using it's embedded JBR which is JDK 17.0.6, I have no problem building app though. 

I thought this is the reason why it builds for you.

**Comment by scubajeff** [comment]
Ok, thanks
