### ISSUE TITLE
Filter by name - UI and usability improvement

### ISSUE THREAD

**Issue by frederikb96** [scubajeff/lespas#126]
First, thank you very much for the new filter by name function , I highly appreciate it. 

I have two aspects that could be improved from my point of view. 

1. Different UI Design to access this feature. If looking at other apps, this feature is normally available via the magnifying glass at the top right of the app and not via the dot menu. If changing this for the main screen, it would also be more consistent with the magnifying glass which is displayed when copying or moving pictures to albums. I understand that you want to keep the UI clean but I think it is more understandable and easier to use this way.

Examples:

Signal:
![Screenshot_20230528-192714_Signal.png](https://github.com/scubajeff/lespas/assets/83548283/d4b29d5f-6aaa-4595-b9ed-12303e999662)

![Screenshot_20230528-192759_Signal.png](https://github.com/scubajeff/lespas/assets/83548283/0bdfc04d-d07f-4e8f-b59f-19866dbdadee)

Mail:
![Screenshot_20230528-192528_K-9 Mail.png](https://github.com/scubajeff/lespas/assets/83548283/d15d84cb-ab3e-452e-8eec-837138071d55)

![Screenshot_20230528-192608_K-9 Mail.png](https://github.com/scubajeff/lespas/assets/83548283/94681c74-96e8-4818-9837-704549206153)

Tasks:
![Screenshot_20230528-192338_Tasks.png](https://github.com/scubajeff/lespas/assets/83548283/bd150717-9e3e-47be-8aee-5ce43010fe2e)

![Screenshot_20230528-192447_Tasks.png](https://github.com/scubajeff/lespas/assets/83548283/2b4e1c2e-09fb-46fb-b048-3b95e9f9146a)

2. Usability improvement: When having an active name filter applied and clicking on an album and returning from the album view back to the main view, the filter is not applied anymore. I guess it is more intuitive to keep the filter applied and this is also helpful when browsing through a set of albums, like all all albums from a specific year.

Thanks!

**Comment by scubajeff** [comment]
I though about issue 1, but there is already a Search menu item there, though I assume not a very welcome feature. 🤣

For issue two, there will be a fix.
