### ISSUE TITLE
Allow storing images on SD card

### ISSUE THREAD

**Issue by BettaGeorge** [scubajeff/lespas#13]
**Is your feature request related to a problem? Please describe.**
Internal storage is notoriously small. I have a large collection of photos, which takes up more internal storage than I can afford to sacrifice, since you need _some_ free internal storage for other apps to keep working.

**Describe the solution you'd like**
Allow moving the app storage to an external SD card via Android's built-in feature.

**Describe alternatives you've considered**
As far as I can see, there is no alternative non-rooting solution because Les Pas stores images in its app storage. For now, I have to limit myself to only having _some_ of my recent photos in Les Pas, which is annoying because there are a hundred gigs of free space on my SD card.

**Comment by scubajeff** [comment]
Please refer to [faq](https://github.com/scubajeff/lespas#faq) section for the reason why lespas stores media files in app's private storage area.

**Comment by BettaGeorge** [comment]
I have read the FAQ, but that is not what this issue pertains to. Android allows app storage to be kept on an external storage device, but the app itself has to support that.

**Comment by scubajeff** [comment]
I might not state it very clear in faq. Use only app's private storage is a intented feature, it's the way to prevent malicious app scanning photos or even uploading them secretly in the background.

**Comment by BettaGeorge** [comment]
I understand that, but my question was _why can't the app's private storage be on the SD card_?

**Comment by scubajeff** [comment]
as far as i know, that's not a per app issue. you can set it in system setting. or did i miss something here? is lespas preventing the system from doing this?

**Comment by BettaGeorge** [comment]
Yes, you can set it in the system settings, but only for apps which explicitly allow it. I have never developed an app that uses this feature, so I am not the leading authority on this, but as far as I understand, the app has to include some code to signal that it can be moved to an SD card. Otherwise, the system setting will be greyed out.

**Comment by scubajeff** [comment]
ok, i will look into that. thanks for the tips.

**Comment by BettaGeorge** [comment]
Thank you, that would be great! I really like this project.

By the way, if you want me to fix up your translations (DeepL produces wrong sentences at times), just point me at the translation files in the git (it's been a while since I've worked with Android) and I'll create a pull request.

**Comment by scubajeff** [comment]
Android allow app installed on external SD card, but according to [Google documents](https://developer.android.com/guide/topics/data/install-location), I quote "The .apk file is saved on the external storage, but all private user data, databases, optimized .dex files, and extracted native code are saved on the internal device memory." That won't fix this issue.

**Comment by scubajeff** [comment]
String resources are located at app/src/main/res folder, in subfolders like values-de, values-es, etc.

**Comment by BettaGeorge** [comment]
Huh. I thought I had read somewhere that you can move use data as well. Maybe I misremembered.

**Comment by scubajeff** [comment]
Spent sometime on the document about scoped storage, seems like starting from Android 10, OS will also prevent app from accessing files created by other apps on external storage too. If further study confirm that Android's mechanism can minimize the risk of malicious file scanning, an option can be added in Les Pas's setting for user to choose from storing photos in internal or external storage.

**Comment by scubajeff** [comment]
latest release 1.5.0 support storing photos on external SD card
