### ISSUE TITLE
Display Of Individual Picture Rotates to Landscape Even if Picture is Portrait Or if App is not allowed to Auto-Rotate

### ISSUE THREAD

**Issue by yuv** [scubajeff/lespas#133]
**Describe the bug**
Since the most recent update (to v2.9.0), when scrolling through pictures/videos the app invariably, immutably, rotates to landscape.  I am not sure if this is an interaction with the app Auto Auto-Rotate (https://f-droid.org/packages/com.jarsilio.android.autoautorotate/) that is one of the most useful apps on the phone and let user decide which apps should auto-rotate and which not.  Les Pas interacted perfectly with it before the update.  I always had Les Pas as one of the few apps which I allowed to auto-rotate.  The problematic behavior happens whether I allow Les Pas to auto-rotate or not. 

**To Reproduce**
1. Start with phone in portrait position 
2. enter Album/Gallery
3. tap on a picture /scroll around.  It does not matter what the picture's orientation is, nor what other settings the user sets elsewhere, the image just rotates to landscape.  portrait pictures have big black strips top and bottom 
4. turn phone to landscape position
5. repeat and observe: if auto-rotating is allowed, the Album/Gallery rotates correctly, but the picture display remains the same, faulty

**Expected behavior**
*If* Autorotate, then based on EXIF.  However, even that one is sometimes wrong, so there should be a settings to either interfere or not with the general phone orientation, with default being not. 

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 11
 - Version 2.9.0

**Comment by scubajeff** [comment]
I have a 1+ 7 Pro, but it's running stock Android 13. Can't recreate this bug. Suspect that there is something wrong with extracting correct picture orientation info from Android's MediaStore. Did it happen as soon as you upgraded to version 2.9.0?

>  portrait pictures have big black strips top and bottom
Can you tell that if the picture is in low resolution? Meaning Les Pas is showing the thumbnail instead of the full size picture.

**Comment by yuv** [comment]
Sorry for the long delay, life happens and this comment was practically finished but I forgot to hit send.

I am sure that the picture is in proper / high resolution, directly from the phone's camera and shown correctly by Simple Gallery Pro (but I generally find Les Pas visually more appealing, even if lately it drives me so nuts that I am seriously considering switching to something else: I need a reliable, easy to use pics browser).

The rotation problem started with the upgrade to 2.9.0.  I also noticed that with the upgrade Gallery has a separate Android album(? not sure about the terminology, sorry) next to Camera.  And it is totally confusing.

I figured out that part of the confusion is that in the Android album shows some of the same pictures as the DCIM/Camera folder.  These are pictures that I have shared over another app.  Why does Les Pas show them?  In DCIM/Camera I have over a 1000 pictures and videos. Simple Gallery Pro lists and shows them correctly.  In reverse chronological order.  This is all I need to manage/display with Les Pas - when I am doing slide shows, it is not on a phone, and not on a tablet either.

I start with the phone in portrait mode - that's how I use the phone 99% of the time.  Les Pas Gallery is pleasant to look at in portrait mode.  Not in landscape mode.

Les Pas -> Gallery -> Android 
* the moment I get into the first picture (portrait), it screws up (mutes) the audio volume
* orientation seems to be according to EXIF and it auto-rotates 
* auto-rotation is annoying in terms of swiping left/right: it literally takes the control away from under my finger and make me want to do something uncivilized to the device
* when I manage to rotate my mind and my fingers to take back control, it is difficult, it interferes with the pulling down of the notification bar, and when I finally manage to get back to the Gallery, it keeps the wrong orientation.
* super-annoying: it seems that Les Pas overrides the system setting not to auto-rotate the screen.  It also overrides the Auto-Auto-Rotate app.  This is IMHO unacceptable.  There is a good reason why a user set not to auto-rotate.  It is not a wish, it is a command.  If Les Pas would behave, I may give it the privilege to auto-rotate.  I did give that privilege to Simple Gallery Pro and while it looks ugly, it functions well.  I still revoked that privilege, because my use case.

Les Pas -> Gallery -> Camera 
* the moment I get into a picture, it screws up (mutes) the audio volume
* orientation is wrong on all portrait pictures
* the audio volume control is kept in landscape position
* when it reaches the first video, it stops the other audio (should mix with it, like Simple Gallery Pro does) and screws up the audio volume
* it does not resume the other audio when swiping away from the video to the next picture

Additionally, there seem to be some interference going on with the screen calibration?

Anyways, Les Pas has become too experimental and definitely not useful to me, sorry.  Simple Gallery Pro is ugly, and does not have the practical function of removing EXIF integrated, but at least it is predictable, functional, and easy to use.  Sorry.

**Comment by scubajeff** [comment]
The upgrade from 2.8.x to 2.9.x is all about new UI for device gallery management. The photo slider code base didn't change much. Therefore, this bug is really a weird one, I'm pretty sure the fix to it could be just a few lines of code change. Anyway, if you wish to switch, that's fine. Appreciate!

**Comment by yuv** [comment]
I don't **wish** to switch.  I **need** a reliable, predictable, intuitive images browser on the phone.  I respect that this app is your toy, and if you want to play with experimental stuff, good for you.  I wish Les Pas to be stable enough not to mess with audio, color balance, display orientation, controls positioning, and selection of gallery / album (photo slider?).  Then I may consider it again.
