### ISSUE TITLE
DCIM and Pictures Backup not starting immediately after enabling

### ISSUE THREAD

**Issue by 0verEngineer** [scubajeff/lespas#135]
**Describe the bug**
I just setup 2.9.0 and manually fixed the directory setup. I let it resync but now i have the problem that the `<lespas home>/Backup/google_pixel 7 pro/` directory is empty, so DCIM and Pictures backup is not working, i can also not find it in the settings of the app anymore.
Sync status: "Last synchronization finished 0 minutes ago."

**To Reproduce**
1. Setup 2.9.0
2. Sync

**Expected behavior**
DCIM and Pictures should be backed up in the `<lespas home>/Backup/google_pixel 7 pro/` dir

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 Pro
 - OS: Android 13, CalyxOS 4.10.1
 - Version 2.9.0

**Comment by scubajeff** [comment]
you mean your old photos or the new ones?

**Comment by 0verEngineer** [comment]
Ah sorry, i discovered i have to click on the gallery and then enable it there, now it is working.

However one detail i just found is it did not start backing up the pictures immediately after i enabled it, i waited about a minute but it did not start. I started it manually in the settings.

**Comment by scubajeff** [comment]
I will figure out a way to deal with it without syncing too frequently.
