### ISSUE TITLE
Subdirectory in pictures directory as sub-album

### ISSUE THREAD

**Issue by 0verEngineer** [scubajeff/lespas#136]
**Is your feature request related to a problem? Please describe.**
The pictures directory in android can contain subdirectories, it would be nice if these can be shown if i go into Gallery->Pictures (a view like the view in Gallery would do the trick)

**Describe the solution you'd like**
A view of the subdirectories in the pictures directory like the Gallery view

**Comment by scubajeff** [comment]
This is already done. I'm ready to release it soon.
