### ISSUE TITLE
Exclude subdirectories in the backup of pictures directory

### ISSUE THREAD

**Issue by 0verEngineer** [scubajeff/lespas#137]
**Is your feature request related to a problem? Please describe.**
I have some directories in my pictures directory i want to exclude from the backup.

**Describe the solution you'd like**
A way to configure subdirectory excludes.

**Comment by 0verEngineer** [comment]
Sorry i found it, you should probably always show the little config icon of an album in the gallery, even if the sync is not enabled (and eventually also show the checkbox to enable sync inside the settings + outside with the cloud icon). I think this would improve the ux.

@scubajeff  i will close this false issue but i hope you consider this little change.

**Comment by scubajeff** [comment]
I prefer hiding the config icon if backup is not enabled. That seems to be a cleaner and more comprehensible UI to me.

**Comment by 0verEngineer** [comment]
It does make more sense the other way IMHO because i had fear of turning it on because i did not know if it starts uploading stuff immediately. So configuration what to upload should definitely be visible before the upload is enabled.
A comprehensible UI lets you configure a feature before enabling it...

But i know that you will insist that you are correct no matter how i try to explain stuff to you.

**Comment by 0verEngineer** [comment]
It is especially confusing the first time you want to turn on a backup. You have designed the UI, of course you know how it works but this is not the way to build good UX design.

**Comment by scubajeff** [comment]
Yes, you are right on this one. A checkbox style control without text hinting is a bad choice, confusing and error-prone. I would change it to a toggle button.

Please don't get things personal. I'm sure you will remember you nailed the one of "eliminating lespas/ folder on server", which I believe every existing user and future ones will agree that's pretty nice. I will not hesitate, at any given moment, to admit that the credit are all yours.
