### ISSUE TITLE
Gallery - Moving should also move/delete folder in archive/backup

### ISSUE THREAD

**Issue by frederikb96** [scubajeff/lespas#138]
There is this new functionality that deleting a photo from the gallery offers you to also delete the one from the archive. I really like this function.

However, when moving the photo from the gallery to a Les Pas album, the photo is not moved or deleted from the archive folder. This does not make sense to me, since this will lead to duplicates on the server. I cannot imagine a case where it makes sense to keep the photo in the archive folder if you are moving it from the gallery folder to a Les Pas album.

So, I would be happy if this could be implemented, as well :)

**Comment by scubajeff** [comment]
Will be fixed in next release.

**Comment by frederikb96** [comment]
I also realized that there is no possibility to view the backup folder located on the server in the Les Pas app anymore. But I guess this is the intended behavior, right?

I guess it is pretty nice, if you don't have to manage two versions of the same folders anymore (local device and server backup), which seems to be possible with the available/upcoming function where you automatically change the content on the server, if deleting/moving pictures on the local device.

If I get it correctly, the goal is to have the possibility of a one-way sync from the local device folders to the backup folder on the server. This means:
- If you add pictures on local device, they are uploaded to the server in the backup folder
- If you move or delete pictures on the local device, this is also synced to the server
- But if you move/delete pictures on the server side in the backup folder, this change should not get synced to the local device. I guess this makes sense, if you consider this to be a backup functionality only.

If I got this correct, it would be probably nice to mention this new functionality briefly in the "About Synchronization" part of the Readme.

**Comment by frederikb96** [comment]
> Will be fixed in next release. I assume a confirmation wouldn't be necessary, just act by the setting

I would be very grateful if this small fix could still be implemented :) Thanks a lot for all the work!

**Comment by scubajeff** [comment]
It's already fixed. No time to release it since I'm not with my development machine for the whole month.

**Comment by frederikb96** [comment]
Ah ok, I see. Nice, thanks for the info!
