### ISSUE TITLE
Address not valid

### ISSUE THREAD

**Issue by kabaga** [scubajeff/lespas#143]
**Describe the bug**
At the very beginning of the app where you have to enter the URL of the Nextcloud instance, I keep getting the error "Address not valid". I could not pass this error.

**To Reproduce**
1. open the Les Pas app
2. Enter the URL of the Nextcloud
3. See error

**Expected behavior**
It is expected to be able to login my Nextcloud instance.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung S21+
 - OS: Android
 - Version: 13

**Additional context**
N/A

**Comment by scubajeff** [comment]
What did you type in?

**Comment by kabaga** [comment]
> What did you type in? 

I entered just my FQDN. Since the scheme is already there, I just entered my FQDN - e.g. sub.domain.tld.

**Comment by scubajeff** [comment]
Did you install Nextcloud in a subfolder? If that's the case your should type in `sub.domain.tld/subfolder`

**Comment by kabaga** [comment]
I don't use subfolders just sub domain.

**Comment by scubajeff** [comment]
That's not a space, just a padding of input box. Please kindly paste the result of
 `curl -X GET 'https://sub.domain.tld/ocs/v2.php/cloud/capabilities' -H "OCS-APIRequest: true"`

**Comment by kabaga** [comment]
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>200</statuscode>
  <message>OK</message>
 </meta>
 <data>
  <version>
   <major>25</major>
   <minor>0</minor>
   <micro>8</micro>
   <string>25.0.8</string>
   <edition></edition>
   <extendedSupport></extendedSupport>
  </version>
  <capabilities>
   <bruteforce>
    <delay>25000</delay>
   </bruteforce>
   <metadataAvailable>
    <size>
     <element>/image\/.*/</element>
    </size>
    <gps>
     <element>/image\/.*/</element>
    </gps>
   </metadataAvailable>
   <spreed>
    <features>
     <element>audio</element>
     <element>video</element>
     <element>chat-v2</element>
     <element>conversation-v4</element>
     <element>guest-signaling</element>
     <element>empty-group-room</element>
     <element>guest-display-names</element>
     <element>multi-room-users</element>
     <element>favorites</element>
     <element>last-room-activity</element>
     <element>no-ping</element>
     <element>system-messages</element>
     <element>delete-messages</element>
     <element>mention-flag</element>
     <element>in-call-flags</element>
     <element>conversation-call-flags</element>
     <element>notification-levels</element>
     <element>invite-groups-and-mails</element>
     <element>locked-one-to-one-rooms</element>
     <element>read-only-rooms</element>
     <element>listable-rooms</element>
     <element>chat-read-marker</element>
     <element>chat-unread</element>
     <element>webinary-lobby</element>
     <element>start-call-flag</element>
     <element>chat-replies</element>
     <element>circles-support</element>
     <element>force-mute</element>
     <element>sip-support</element>
     <element>sip-support-nopin</element>
     <element>chat-read-status</element>
     <element>phonebook-search</element>
     <element>raise-hand</element>
     <element>room-description</element>
     <element>rich-object-sharing</element>
     <element>temp-user-avatar-api</element>
     <element>geo-location-sharing</element>
     <element>voice-message-sharing</element>
     <element>signaling-v3</element>
     <element>publishing-permissions</element>
     <element>clear-history</element>
     <element>direct-mention-flag</element>
     <element>notification-calls</element>
     <element>conversation-permissions</element>
     <element>rich-object-list-media</element>
     <element>rich-object-delete</element>
     <element>unified-search</element>
     <element>chat-permission</element>
     <element>silent-send</element>
     <element>silent-call</element>
     <element>send-call-notification</element>
     <element>talk-polls</element>
     <element>message-expiration</element>
     <element>reactions</element>
     <element>chat-reference-id</element>
    </features>
    <config>
     <attachments>
      <allowed></allowed>
     </attachments>
     <call>
      <enabled>1</enabled>
     </call>
     <chat>
      <max-length>32000</max-length>
      <read-privacy>0</read-privacy>
     </chat>
     <conversations>
      <can-create></can-create>
     </conversations>
     <previews>
      <max-gif-size>3145728</max-gif-size>
     </previews>
     <signaling>
      <session-ping-limit>200</session-ping-limit>
      <hello-v2-token-key>-----BEGIN PUBLIC KEY-----
MFkwEwY4KoZIzj0CAQYIKoZIzj0DAQcDQgAEQUEjLEPe9K3RF9Hz4orRi1NwuUC0
SMYF76GUPk9RQeG+aIqq3xzYC5sIFS0jTsrXMYnYuAuupd6fGLirTC/M3Q==
-----END PUBLIC KEY-----
</hello-v2-token-key>
     </signaling>
    </config>
    <version>15.0.6</version>
   </spreed>
   <theming>
    <name>Nextcloud</name>
    <url>https://nextcloud.com</url>
    <slogan>a safe home for all your data</slogan>
    <color>#0082c9</color>
    <color-text>#ffffff</color-text>
    <color-element>#0082c9</color-element>
    <color-element-bright>#0082c9</color-element-bright>
    <color-element-dark>#0082c9</color-element-dark>
    <logo>https://sub.domain.tld/index.php/apps/theming/image/logo?useSvg=1&amp;v=4</logo>
    <background>https://sub.domain.tld/core/img/background.png?v=4</background>
    <background-plain></background-plain>
    <background-default>1</background-default>
    <logoheader>https://sub.domain.tld/index.php/apps/theming/image/logo?useSvg=1&amp;v=4</logoheader>
    <favicon>https://sub.domain.tld/index.php/apps/theming/image/logo?useSvg=1&amp;v=4</favicon>
   </theming>
  </capabilities>
 </data>
</ocs>

```

**Comment by scubajeff** [comment]
Seems quite normal. Can I access your server? I need to do some debugging stuff. You don't have to create account for me. You could email me your server address at scubajeffrey@protonmail.ch

**Comment by scubajeff** [comment]
I have successfully load the login page of your server and also `curl` works here too. But when I try to login using Les Pas, your server response 403 error. Is your http server has some security settings which prevent access from certain client? Like some specific user agents, etc.?

**Comment by kabaga** [comment]
When I entered the URL to Les Pas, I don't even see any traffic coming from my phone or tablet. I have a regular nextcloud app and it works just fine. I am not exactly sure what you mean about user agent

**Comment by scubajeff** [comment]
After login from the app, you can check your server's http access log, try search for `LesPas` in this log file, it will give us hint what went wrong.

**Comment by kabaga** [comment]
I checked the nginx logs and don't see the ```LesPas``` keyword at all.

**Comment by scubajeff** [comment]
Could you try searching for error 403 in the server log file?

**Comment by kabaga** [comment]
The only time I see a log hit if I don't use Les Pas. For example, if I used the mobile browser, nextcloud app, I could see the http status 200. With Les Pas, I don't see any logs at all on my nginx. However, when I checked my Firewall (OPNsense), I could see a traffic hitting the firewall which was allowed. NGINX was not showing me anything.

If I used the private IP of my Nextcloud on Les Pas with HTTP, I get it worked and got to the login prompt, but I do not want to bypass the NGINX. If it matters, I am using the OPNsense NGINX plugins for my reverse-proxy needs.

If I disconnect from my wifi and use LTE, I could see from my firewall logs that the Les Pas is using port 80/tcp despite I selected HTTPS. I did not have port 80/tcp enabled. I added port 80/tcp and the firewall logs showed 443/tcp, but I still cannot see any HTTP logs from Les Pas.

**Comment by scubajeff** [comment]
I tried on several phones I have. The result are the same, Les Pas won't connect and browser access is normal. This is weird! But I also have a feeling that the fix could be a quick one. Working on it.

**Comment by scubajeff** [comment]
Is it possible to disable the firewall for a while and test the login again? Looks more and more like a firewall issue to me.

**Comment by kabaga** [comment]
It is not possible to disable the firewall. If I disable the firewall, I would need to connect the Nextcloud VM directly to the modem. It is not possible in my case.

**Comment by scubajeff** [comment]
No problem. Let me try some different configs for okhttp on my side.

**Comment by teto** [comment]
I have a similiar issue. I dont see anything in the logs apart from a bunch of "unable to generate route:
```
"GET","url":"/index.php/204","message":"{\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"photos.page.index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":[{\"file\
```
I am running nextcloud 27
I tried running `curl -X GET 'https://sub.domain.tld/ocs/v2.php/cloud/capabilities' -H "OCS-APIRequest: true"` but got.

```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>503</statuscode>
  <message>Service unavailable</message>
 </meta>
 <data/>
</ocs>
```

I can send via mail/create an account on my VPS if that helps.

**Comment by scubajeff** [comment]
@teto Your case might not be the same as OP. Are you self-hosting or running a managed instance from ISP. There was a similar case earlier when ISP won't provide some Nextcloud API endpoints.

**Comment by teto** [comment]
I am self hosting with a nixos-based install. This is the nix config https://github.com/teto/home/blob/main/hosts/neotokyo/nextcloud.nix but even without knowing nix some settings should be transparent. https://docs.nextcloud.com/server/latest/developer_manual/core/externalapi.html#authentication-basics mentions that I should try with authentication but it didnt change anything.  I tried the command from within VPS too (but https wouldn't let me use "localhost" as domain). I wonder if this is some missing setting in nginx . I will try to ask in #nextcloud, I welcome ideas :)

**Comment by scubajeff** [comment]
@teto If my memory is correct, Capability is a seperate module of Nextcloud. Have you packaged it?

**Comment by scubajeff** [comment]
@kabaga Ok, when using user agent `curl/7.81.0`, I can get the correct login screen shown, while the default okhttp user agent `okhttp/4.9.0`, which Les Pas uses to ping Nextcloud server's 'capabilities' endpoint, yield a http error 403. This is clearly triggered by a  firewall setting which filter on client's user agent. 

Although Les Pas can emulate a common user agent, but I would like to stick with current custom setting for better debugging purpose. So could you please check again your firewall setting?

**Comment by kabaga** [comment]
What needs to be added or modify to the NGINX for this to work?

**Comment by scubajeff** [comment]
Great! 😃

**Comment by scubajeff** [comment]
According to this [issue](https://github.com/opnsense/plugins/issues/2175) of OPNsence, it will block user agent of `'okhttp'` specifically. I will update the code to use `'curl'` in the coming release for the 'capabilities' ping call. 

@kabaga Please don't close this issue yet, and keep monitoring it until it's fixed by my code push. Then after you install the new release of LesPas, you can try enable the "bot protection" again.

**Comment by teto** [comment]
I've updated the android app and it solved the issue for. Thanks !
