### ISSUE TITLE
No release at https://apps.nextcloud.com/apps/les_pas_photo_app_for_android_phone

### ISSUE THREAD

**Issue by teto** [scubajeff/lespas#145]
**Is your feature request related to a problem? Please describe.**
I am trying to package lespas for my linux distribution. The packaging of nextcloud apps is done by this software that for some reason can't package lespas https://github.com/helsinki-systems/nc4nix/issues/10
My guess is that no release is listed at https://apps.nextcloud.com/apps/les_pas_photo_app_for_android_phone contrary to https://apps.nextcloud.com/apps/maps for instance.

**Describe the solution you'd like**
I would like a release to appear on the official apps.nextcloud.com (for nextcloud 27 at least since that's the one I am using).

**Describe alternatives you've considered**
I dont know enough about nextcloud apps to present an alternative.

**Comment by scubajeff** [comment]
Les Pas is an Android app, you can install it from Google Play Store, F-Droid and github. It's a pure mobile solution, nothing needed to be installed on Nextcloud server.

There are at least two types of listing on Nextcloud market, App and Integration. Les Pas is the later one.

**Comment by teto** [comment]
oh sh** sry I misunderstood that part ! that's greater. From the description, lespas seems to be the only solution that ticks everything I am looking for so very eager to try. Closing then and thanks for everything.

**Comment by scubajeff** [comment]
Though you don't have to install anything on Nextcloud for using Les Pas, you'd better set up Preview Genrator Nextcloud app. There is detail instruction on how to customize it in FAQ
