### ISSUE TITLE
blog feature is never enabled

### ISSUE THREAD

**Issue by jwalt** [scubajeff/lespas#146]
**Describe the bug**
I am unable to get the blog feature working. I have installed cms_pico and the lespas theme according to the manual, but the blog menu entry stays greyed out.

**To Reproduce**
1. Setup nextcloud as instructed
2. Go to any album in lespas
3. Find the Blog menu entry greyed out

**Expected behavior**
Blogging feature working as described.

**Smartphone (please complete the following information):**
 - Device: Poco F3
 - OS: LineageOS
 - Version 18

**Additional context**
There is no indication of an error in the nextcloud logs, even on "DEBUG" log level, but the apache access log shows the following two entries that seem to match the code in `refreshBlog` (NCShareModel.kt)

```
localhost:80 10.26.102.1 - jwalt [20/Aug/2023:00:20:11 +0200] "GET /csrftoken HTTP/1.1" 200 1947 "-" "LesPas_v2.9.1"
localhost:80 10.26.102.1 - jwalt [20/Aug/2023:00:20:11 +0200] "GET /index.php/apps/cms_pico/personal/websites HTTP/1.1" 412 1287 "-" "LesPas_v2.9.1"
```

Note the error code 412 on the second request.

**Comment by scubajeff** [comment]
Have you follow the setup instructions at [pico_lespas](https://github.com/scubajeff/pico_lespas#installation)

**Comment by jwalt** [comment]
Yes, the theme is available and enabled. It is the second web request (shown in the log) that returns an error code. After that, lespas does not perform any pico-related calls anymore. I can create pico-cms sites using the regular web interface just fine.

In the meantime I was able to look at the incoming request, and it seems to be okay... there is a requesttoken header and the cookies. Obviously I can't tell if they are correct, but they certainly look like cryptography stuff (i.e. random-looking strings). This is NextCloud 27, btw.

**Comment by jwalt** [comment]
I found the problem. The root cause is an annoying behaviour of NextCloud that is technically in spec, but bug-prone. For API requests, it sends multiple `set-cookie` headers with different session IDs. This does nit just happen with lespas, I see it with other apps as well. It might be this issue: https://github.com/nextcloud/server/issues/26267 that seems to have occurred in version 21 at least.

Now, according to https://stackoverflow.com/questions/3806132/multiple-set-cookie-headers-in-http this is allowed, albeit error-prone (as we see here). The last value is supposed to take effect. However, lespas uses the first value. When adding some fixup code to my reverse proxy to filter out the invalid duplicates, lespas enables the blogging feature.

My suggestion is to change the code to use the last session cookie value, like other nextcloud-using apps also do. Unfortunately, I am not experienced in your app development environment.

**Comment by scubajeff** [comment]
Thanks for the hints! I'll try to incoporate this in the coming release.

**Comment by jwalt** [comment]
I fear the patch is not sufficient for newer NextCloud versions. In NextCloud 27, the session ID cookie is no longer `oc[a-fA-F0-9]{10}=` but `[a-fA-F0-9]{13}=` (guessing, I have only one data point).

**Comment by jwalt** [comment]
There is no `ocxxxxx` anymore in NextCloud 27, instead there is this new name. That new cookie is duplicated just like the previous `ocxxxxx`.
