### ISSUE TITLE
Internal Sharing stops working

### ISSUE THREAD

**Issue by DaJansenGit** [scubajeff/lespas#149]
**Describe the bug**
After a not yet clearly reproducible time (around 1day) after setting up Les Pas app, I can't do internal shares with other accounts on nextcloud anymore. I can go the menu but Les Pas doesn't show me the accounts to share with anymore. Direct after setup of the app it works fine and the sharing itself also works. The previously created shares still exist and work. 
I can also see in Nextcloud App, that the previously created shares are existing, but Les Pas Stopps showing me the previously shared accounts (first letter of shared account next to the name of the shared album in album overview mainpage)

**Expected behavior**
Be able to share albums with other nextcloud users anytime, not only shortly after setup of the app. 

**Smartphone (please complete the following information):**
 - Device: S21 Ultra (Android)
 - OS: Nextcloud docker container by linuxserver
 - Version: Les Pas v 2.9.2, Nextcloud v 27.0.2

**Additional context**
I made sure that all users are in a group like described in readme.md. And as described above it works for some time and then suddenly stops working. 

Any idea where I can look for logs that might help? 

Apart from that: thanks for the amazing app, this seems finally to be a good way to get away from Google Photos :)

**Comment by scubajeff** [comment]
seems like Nextcloud share and sharee API endpoint failing. being tied up on some other thing right now, will let you know how to do some testing later.

**Comment by scubajeff** [comment]
If you have curl install in your system, what do you get from the following:
```
curl -u your_userid:your_password  -X GET 'https://your_server_address/ocs/v1.php/apps/files_sharing/api/v1/sharees?itemType=file&format=json' -H "OCS-APIRequest: true"
```

**Comment by scubajeff** [comment]
Did you accidentally disable this one in administrator setting?
![Screenshot from 2023-09-27 11-59-40](https://github.com/scubajeff/lespas/assets/458032/10fb334d-b47a-4ec8-8a6b-f826e2e73920)

**Comment by DaJansenGit** [comment]
Hi @scubajeff, sorry for the late feedback. Yesterday I noticed that sharing only does not work when there is a pending sync. Once the sync is complete, items can be shared and shared. Is this intentional? If so, can the issue be closed here. I didn't find anything about this in the documentation unfortunately.

**Comment by scubajeff** [comment]
No, syncing and sharing are controlled by two different functions. But I will review the code. We can close this issue for now.
