### ISSUE TITLE
Feature: Backup Gallery - move instead of delete + upload

### ISSUE THREAD

**Issue by frederikb96** [scubajeff/lespas#150]
First, I am very happy with the current Backup Gallery functionality and workflow of Les Pas, thanks :)

However, one improvement could be to trigger a move on the sever for already backed up files if you move those via Les Pas to a album instead of deleting the file from the server and uploading it again from the phone to the server.

Reproduce:
1. In Les Pas activate the Backup function for a gallery folder, wait till backed up.
2. Move the file from the gallery to a album
3. The file is uploaded again from the phone to the new album and the backup file on the server is deleted

Desired:
- If move is triggered, check for each file if it is available in the server backup, if so trigger a move on the server instead of a delete and a upload from phone
- This is especially useful if users back up a huge amount of files and later move those, in this case hundreds of GB need to be uploaded again.

There are different cases one clould consider, I will try to list those as far as I understand it, but I have no idea how Les Pas is handling the sync so maybe I make wrong assumptions here:
- File already backed up, do a move
  - Trigger move on server to album
  - If successful, delete file from phone gallery and sync cache from server to phone
  - Or do a parallel move on the phone, which might be useful for albums set to local (not sure how Les Pas is handling this  normally :)) to reduce network usage even more 
- File already backed up, do a copy
  - Same as with move but trigger a copy on server and a copy on phone
- File not backed up or move or copy on server failed
  - do it the normal way as it is handled right now

**Comment by scubajeff** [comment]
😀, I'm actually working on a feature now on reducing client to server traffic, when the source file is already available on server, involving the case like copy/move photo among albums and friend's publication. It will also ensure meta data saved in the sidecar file (like caption, geotag, modified taken date, etc) won't get lost in the middle of the process. Your idea is definitely an good addition!

But I have to tell you, this feature is quite a tidious job, have to revisit a lot of old code and do test after test for each and every situation.

**Comment by frederikb96** [comment]
Ah nice, sounds cool. Yeah no rush 👍

**Comment by scubajeff** [comment]
latest release has these features built in
