### ISSUE TITLE
Not all directories can be accessed

### ISSUE THREAD

**Issue by patman-cp** [scubajeff/lespas#155]
**Describe the bug**
Not all folders / albums / images are showing up. 

**To Reproduce**
1. Connect to Nextcloud
2. Set to use my "Photos" directory
3. Look at folders / albums that show up
4. Many are missing

**Expected behavior**
All folders / images should show up.

**Screenshots**
During the initial setup, you can see there are 5 directories under "Photos":

![image](https://github.com/scubajeff/lespas/assets/42042889/a76a42bd-f283-4f86-9e89-26c57c83765d)

But only these 3 directories / albums can be seen after that:

![image](https://github.com/scubajeff/lespas/assets/42042889/1b90d1a2-04c1-47b6-aff0-4fea262215d5)

**Smartphone (please complete the following information):**
 - Device: Samsung S9
 - OS: Android 10
 - Version: Les Pas 2.9.6, Nextcloud 27.1.3

**Additional context**

**Comment by scubajeff** [comment]
Les Pas does not support nested folders, there is no sub-album of an album. So I believe the folder 'Trips' has sub-folder in it. For folder 'Backup', it is created by Les Pas for storing photo backup from your device's gallery, it will not be listed as an album.
