### ISSUE TITLE
Cannot use ipv6 as address

### ISSUE THREAD

**Issue by xor2003** [scubajeff/lespas#16]
Cannot enter ipv6 like https
://[200:5817:28d3::da33] as address.
also I think both http and https should work.

**Comment by scubajeff** [comment]
will check ipv6 address issue, probably it's a regex glitch. for http, i'm not gonna support it. it's easy to setup a letsencrypt certificate nowaday.

**Comment by xor2003** [comment]
I understand your point I'm asking about http because in case of yggdrasil network it is double encryption

**Comment by scubajeff** [comment]
it has a long way to go to replace https
