### ISSUE TITLE
SyLespas Sync stucked at large File

### ISSUE THREAD

**Issue by Grassfreater** [scubajeff/lespas#160]
First, I´m Sorry, I´m not that good in programming and find failers in ANdroid, but I´ll try my best, ..
My lespas Folder is about 10GB large and I started to sync Photos and Video files. 
It worked well but suddenly it stopt syncing.
I´m looking for the status and its making lokal Changes  and try to add a Video File.

I can see the file in lespas, but I cant find it on the Smartphone.

I´d love to copy the larg video via USB and then delete it, so the syncronisation could work again.

So two questions.

1. is there a way to ignore that file at next sync?
2. where are the files stored lokaly so I can delete it?

 - Device: Xiaomi redmi note 8T
 - OS: MIUI 12.5.2Stable
 - Version Lespas V2.9.6
 - Version Nextcloud 28.0.1

Thx for your Help!!!

**Comment by scubajeff** [comment]
Find the file in Les Pas, click on it and it will start playing, while it's playing, touch the screen to reveal the bottom bar menu, you will see it's full path there.

I have also experienced a weird bug in one of my testing phones which prevent a large file from uploading. It might be the same case as the one you're facing right now. It was fixed yesterday and will be included in next release.

**Comment by Grassfreater** [comment]
Hey, thx for your superfast response!
But I can only see the name of the Video, not the path.

**Comment by Grassfreater** [comment]
Hey, thx for your superfast response!
But I can only see the name of the Video, not the path. 

When I search for the file in my System, I can't find it ,..

**Comment by Grassfreater** [comment]
Sorry for the double post, ..

**Comment by scubajeff** [comment]
If you don't mind, could you please post a screenshot when the bottom bar menu is showing?

**Comment by Grassfreater** [comment]
Hey, sorry, it took a while to get the Screenshots in this form, .. Attached the Pictures.
When I look up a other file, it shows the path as you promised, ..

![Screenshot_2024-01-21-00-22-59-574_site leos apps lespas](https://github.com/scubajeff/lespas/assets/57747023/af2ff2d0-5d75-4eac-93d8-8a27c36587ef)
![Screenshot_2024-01-21-00-24-13-387_site leos apps lespas](https://github.com/scubajeff/lespas/assets/57747023/ca4f433a-61f8-4a43-874a-b58661bdf9df)
![Screenshot_2024-01-21-13-03-44-125_site leos apps lespas](https://github.com/scubajeff/lespas/assets/57747023/b50d732e-444d-491e-93e7-19cd54378449)
![Screenshot_2024-01-21-13-03-52-930_site leos apps lespas](https://github.com/scubajeff/lespas/assets/57747023/0216c127-11fa-4a18-8a23-738261d083c2)

**Comment by scubajeff** [comment]
I see. It's not a file in phone's gallery, but file in Les Pas's album.

There's no simple way to copy this video file out of the album in release 2.9.6. You have to install the latest 2.9.7 which will be published to f-droid very soon. In this new version, you can select this file and export it to your phone's 'Download' folder, then you can delete it from the album and see if the sync process can move on.

Sorry for the inconvenience!

**Comment by Grassfreater** [comment]
Hey, its cool to know that a solution is coming!
thx for your Help/your Work!!!

All the Best!

**Comment by Grassfreater** [comment]
Hey, its cool to know that a solution is coming!
thx for your Help/your Work!!!

All the Best!

**Comment by Grassfreater** [comment]
![Screenshot_2024-02-05-09-48-58-514_site leos apps lespas](https://github.com/scubajeff/lespas/assets/57747023/ffcef940-ba12-4c1f-af77-8194035eb270)

**Comment by Grassfreater** [comment]
Hey, I could export it! Share didn't work.  I did export it and then deleted the large files. But now the sync is stuckt while deleting the files, .. 
Any guess?
