### ISSUE TITLE
Muzei Widget "link" 

### ISSUE THREAD

**Issue by steviehs** [scubajeff/lespas#161]
I love the "memories" feature to set new backgrounds with Muzei and for an easy lookup, when this picture was happening, I use the Muzei widget, which then opens the album containing this picture.

But this only works correctly, if the les pas app is not open and kept in background at this time. If lespas was already open, it will just show up with the last album or overview and not switch into the album containing the picture of the Muzei widget.

Reproduction:

let muzei show a pict from album a and open this album in lespas via muzei widget. switch to the desktop and keep lespas open in background and let muzei show a new pict from album b. If you now click on the new pic in the muzei widget, it still shows album a.  It should be b 

Version is 2.9.6

And as always: thank you so much for lespas!!!!

**Comment by scubajeff** [comment]
This is related to Android's task and back stack management. I have tried many different combinations, doesn't have a clue so far, must be missing something. Will keep trying.

**Comment by steviehs** [comment]
> This is related to Android's task and back stack management. I have tried many different combinations, doesn't have a clue so far, must be missing something. Will keep trying.

Don't try too hard if this is the only issue :-) I just have to kill lespas and everything is fine then.
