### ISSUE TITLE
Muzei Integration additional options

### ISSUE THREAD

**Issue by dave7895** [scubajeff/lespas#167]
**Is your feature request related to a problem? Please describe.**
I love the Muzei Integration, especially the feature where pictures you have taken on this date in a past year. But I have the problem that the pictures I have cover only mostly strongly clustered time frames e.g. some week long vacation. So I find myself often switching between the recent and the today in history choice.

**Describe the solution you'd like**
I would love for there to be the option to chain the two alternatives to random one after another. I am no Kotlin expert but I think I would be able to pull the logic out and create the feature.

**Comment by dave7895** [comment]
Alright! I would probably just plug together the existing code for the two
options of today in history > recent and recent > today in history and
possibly try to find a good option for the text/localisation, that fine?

Il lun 29 apr 2024, 13:27 scubajeff ***@***.***> ha scritto:

**Comment by scubajeff** [comment]
Ok
