### ISSUE TITLE
App only Syncs some Folders

### ISSUE THREAD

**Issue by MetalNeo** [scubajeff/lespas#17]
**Describe the bug**
I have been having issues getting the app to sync all of my folders and pictures/videos in my Nextcloud server. The files are in the correct place, within `/lespas`, but only 37 of the ~350 albums actually appear.

**To Reproduce**
1. Create 350 folders with images directly beneath them in `/lespas`.
2. Open and sign into Les Pas.
3. Wait for albums to start syncing.
4. Albums eventually stop syncing, regardless of how much time has passed.

**Expected behavior**
All of the albums should appear in the app.

**Smartphone (please complete the following information):**
 - Device: Oneplus 5
 - OS: Android 11
 - Browser N/A
 - Version 2.0.4

**Additional context**
I have tried restarting the app, restarting the phone, logging out and back in, disabling battery optimization, and changing my DNS server without any change in behavior.

I have not set up user sharing or image previews on my server. I have also ensured I have enough storage space on my phone for additional pictures.

**Comment by scubajeff** [comment]
It's so strange, github android client on my phone didn't pick this issue up. So are you still interesting in testing this app? If yes, could you please try to find out where exactly the sync stop? Les Pas sync album one by one, so the last incomplete album should be the one it's working on, and the last picture within it should be stop place, then find out what is the next picture it should but not able to sync. 

btw, 350 albums seems a little bit exaggerate, not sure how you can manage them on phone.

**Comment by scubajeff** [comment]
It's wired, github android client on my phone didn't pick this issue up in time.

So are you still interesting in testing this app? If yes, could you please try to find out where exactly the sync stop? Les Pas sync album one by one, so the last incomplete album should be the one it's working on, and the last picture within it should be stop place, then find out what is the next picture it should but not able to sync. 

btw, 350 albums seems a little bit exaggerate, not sure how you can manage them on phone.

**Comment by scubajeff** [comment]
It's wired, github android client on my phone didn't pick this issue up in time.

So are you still interesting in testing this app? If yes, could you please try to find out where exactly the sync stop? Les Pas sync album one by one, so the last incomplete album should be the one it's working on, and the last picture within it should be stop place, then find out what is the next picture it should but not able to sync. 

btw, 350 albums seems a little bit exaggerate, not sure how you can manage them on phone.

**Comment by MetalNeo** [comment]
Thank you for the reply! I think I figured it out. It seems that the syncing was getting stuck on a folder that didn't contain any pictures. Removing the folder appears to have resolved the issue.

**Comment by scubajeff** [comment]
Oh, that surely is a bug, I will try to fix it in next release. BTW, are all those 350 albums really in your Les Pas app now?

**Comment by MetalNeo** [comment]
I needed to move/change some of them, but yes. The sync seemed to also be getting stuck when there are incompatible file types (eg .txt or .gif) in the directory, as well as pictures which contained characters that the app didn't like. Not exactly sure, but it seemed to be space characters or bracket characters that was causing the issue.

I can create separate issue reports for these to help organize them.

**Comment by scubajeff** [comment]
Les Pas support file types which Android suppprt, e.g., jpeg, gif, bmp, png, webp, also support animated gif and webp on Android version 9 and above. It will screen out  file types it doesn't suppprt  during the sync, hence the stuck you are facing is not because of the type. Please create an seperate issue. And thank you for doing these tests with me.
