### ISSUE TITLE
Timestamp / Creation Date when moving from phone or backup

### ISSUE THREAD

**Issue by GottHeit** [scubajeff/lespas#174]
**Describe the bug**
If moving a picture to a remote album it is always getting the "now"-timestamp. It happens when moving from phone and/or backed up pictures from camera roll. Didn´t except this to happen, at least from backup, as they are already uploaded to nextcloud - where they have the correct timestamp. 

**To Reproduce**
1. Go to 'Gallery'
2. Click on 'Picture' and choose 'Moving' and select Remote Album to move to
3. Check timestamp of picture in remote album

**Expected behavior**
As written at least the timestamp of already uploaded pictures in backup should be kept. Better if every picture moved to an remote album keeps its timestamp. 

**Screenshots**
![Screenshot_20240622-095233](https://github.com/scubajeff/lespas/assets/17480327/1abec111-8271-48ee-9d58-68fb6a1708ad)
timestamp on phone

![Screenshot 2024-06-22 095451](https://github.com/scubajeff/lespas/assets/17480327/f113829c-7a02-4cc6-9ad4-35b24efc16e3)
timestamp of backup in nextcloud

![Screenshot_20240622-095544~2](https://github.com/scubajeff/lespas/assets/17480327/bf166bfa-64d1-4e99-b0a7-430c78899532)
moving to remote album

![Screenshot 2024-06-22 095650](https://github.com/scubajeff/lespas/assets/17480327/daff0934-cf27-4553-b4af-63cad843de59)
timestamp after moving

**Smartphone (please complete the following information):**
Pixel 5
Android 14
2.9.10

Mabe I am overlooking something, so would be grateful if pointed to the right direction :) 

If not it would be great if this would be possible as I really like the app otherwise

**Comment by scubajeff** [comment]
Your media file might not have a timestamp recorded in its EXIF. But from the screenshot you posted, the timestamp can be extracted from its filename. I will add this in the next release.

**Comment by GottHeit** [comment]
Thanks :)

And sorry, I should have mentioned. Lespas for itsself recognizes EXIF Data, so pictures are shown in chronological order in Lespas, but the file date is changed to the moment when moving to an album. So in nextcloud the order isn´t correct anymore.

So file date was something like 
11.06.24 22:10 before moving an
23.06.24 12:12 after moving 
even if files were already uploaded via backup from camera roll

Here is another example :)

Bevor moving:
![Screenshot_20240623-121826](https://github.com/scubajeff/lespas/assets/17480327/d9ee01fd-29d2-47ad-8be0-2879b3a16cda)

After moving (it says file date "19 seconds" 
![Screenshot 2024-06-23 121940](https://github.com/scubajeff/lespas/assets/17480327/5947708f-6a16-4b78-9cd2-bf26eed73670)

In Lespas:
![Screenshot_20240623-121913](https://github.com/scubajeff/lespas/assets/17480327/1fd1dbca-e226-482f-bc49-325cc2e3552a)

**Comment by scubajeff** [comment]
Where is the second screenshot of your last post coming from? Do you mean the date/time miss match happens in Nextcloud file app rather than Les Pas?

**Comment by GottHeit** [comment]
No, the file date changes everywhere - right after i move a file in Lespas. 

The file date - as you can see in screenshot one - was 08.06.24 before moving.


The second screenshot was right out of the nextcloud frontend. Here is full screen of nextcloud app, where you can seee the file date ist now 23.06.24 
![Screenshot_20240624-091727](https://github.com/scubajeff/lespas/assets/17480327/c77e36eb-dc54-4c01-a9f6-023fdf1a95c7)

**Comment by scubajeff** [comment]
Ok, the date miss-match you see is from Nextcloud's Android client. Could you please also confirm the same happens in Android's own File app?

**Comment by GottHeit** [comment]
Did an upload via Nextcloud app.

First screen Phone Storage, second uploaded file. File date stays the same...

![Screenshot_20240625-083532~2](https://github.com/scubajeff/lespas/assets/17480327/c5e04863-2cb4-4ac3-952b-89847d9b9e7c)

![Screenshot_20240625-083559](https://github.com/scubajeff/lespas/assets/17480327/9dfebb34-5b99-4250-a64e-2d4a54372a2b)

**Comment by scubajeff** [comment]
I just did a test on my Pixel phone:

1. Open Les Pas's Gallery, find a file dated on June 21, then add it to Les Pas
2. The file date stays the same in Les Pas's Gallery list
3. Quit Les Pas, then open Android File app, the date of the file stays the same
4. I don't have Nextcloud's client app installed, so I can't test it at this moment

Seems like I can't replicate this bug here. Or did I miss something?

**Comment by GottHeit** [comment]
Thanks again! Hmm, maybe I am doing something wrong. 

1. Did (Screen 1)
2. Correct (Screen 2 - because of exif or other file information?)
3. File is deleted afterwards because it was uploaded to Nextcloud (to use that and save space on phone, of course)
4. In Nextcloud file is then dated to actual time and date (Screen 3)

How I use Les Pas (sorry for misspeling the name before)
1. Open app - Phone gallery is shown
2. Open phone gallery and then camera folder e.g. (or else, doesn´t depend)
3. Choose a random photo frome date before today
4. Hit Les Pas button and select moving to a imported archiv/backup folder from nextcloud
5. Delete original photo in Les Pas pop up

Screen 1 (Picture from Wednesday):
![Screenshot_20240628-102352](https://github.com/scubajeff/lespas/assets/17480327/e3f16a44-8155-4fd7-8d6d-65159864d1d3)

Screen2 (after moving):
![Screenshot_20240628-102455~2](https://github.com/scubajeff/lespas/assets/17480327/57633aaf-af4d-4c10-bf1e-47b8fda34b7b)

Screen 3 (in Nextcloud afterwards date is set to today):
![Screenshot_20240628-102807](https://github.com/scubajeff/lespas/assets/17480327/24e5afe0-9cde-43c0-a970-18405fa991fc)
