### ISSUE TITLE
Lockin impossible, no QR code scaner

### ISSUE THREAD

**Issue by acht** [scubajeff/lespas#178]
Hi,

if I try to set up Les Pas via URL I end in a white screen. (Reproduced on multiple devices wit different F-Drod versions.)

The QR login is working well. But it is unclear how to enable QR login. It took me a lot of time to find the information to install a compatible QR scanner.

My suggestion is to add the information to the screen displayed on first opening the app and on the settings page. E.g.:
"To enable QR-based login install a ZXing compatible App like Barcode-Scanner" Also a link to install a compatible app is very welcome. I used Barcode-Scanner from F-Droid.

To add the information on the suggested positions should be a minimal effort and would be very helpful for many users.

Thanks!

**Comment by scubajeff** [comment]
Thank you for the suggestion. I'm planning to integrate ZXing's library later, then no external apps will be needed for QR code login.

**Comment by scubajeff** [comment]
2nd thought, your idea might be better than integrating ZXing library.
