### ISSUE TITLE
Tab to Swipe (next image)

### ISSUE THREAD

**Issue by DieWebsitemacherei** [scubajeff/lespas#179]
**Is your feature request related to a problem? Please describe.**
When swiping through the gallery I always need to one-tap the image to activate swipe / to focus the displayed asset. This way a fast swipe is not possible. 

**Describe the solution you'd like**
Autofocus the displayed asset

**Describe alternatives you've considered**
A checkbox to enable or disable "autofocus"

**Additional context**
Im using Xiaomi Phones (Note12pro / 9SE) with original OS.
Energy saving mode off for lespas.

**Comment by scubajeff** [comment]
Can you find out the Android version of your phone?

**Comment by DieWebsitemacherei** [comment]
Oh my... sorry for wasting your time! Its Android11. Never thought that it would be a android thing.

Testet on another phone with android 12 there is everything working as expected.

**Comment by scubajeff** [comment]
Most likely Xiaomi thing.
