### ISSUE TITLE
Question : Files placed in albums

### ISSUE THREAD

**Issue by ventoux84** [scubajeff/lespas#181]
It's a question, not a bug.
Are the files placed in an album duplicated ?
I made a first backup of my phone photos on my Nextcloud server using LesPas.

Then on my phone, using LesPas, I chosed a photo to put in an album created for the occasion.
On the server, the photo is in both the backup directory and the album directory.

Is this the way it's supposed to be, or have I made a mistake?
Tanks.

**Comment by scubajeff** [comment]
It's what it supposed to be. When you want to add a picture to an album, you can choose between copy or move action.

**Comment by ventoux84** [comment]
thanks for this reply
