### ISSUE TITLE
Directory with sub-directories

### ISSUE THREAD

**Issue by ventoux84** [scubajeff/lespas#182]
It's a question, not a bug.
Can Lespas synchronize a directory on the Nextcloud server that contains other directories with photos, and then display all the images on the smartphone?

I can't do that.

**Comment by scubajeff** [comment]
An album shown in your phone is a sub-directory in your server's lespas folder. Albums within album is not supported.

**Comment by ventoux84** [comment]
Thanks, this app in not for me.
