### ISSUE TITLE
New Folders no Longer Syncing after Removing Albums

### ISSUE THREAD

**Issue by MetalNeo** [scubajeff/lespas#19]
**Describe the bug**
New albums added after recent update are not automatically syncing when opening the app.

**To Reproduce**
1. Create a synced folder.
2. Copy to a new folder with a different name in `/lespas` from Nextcloud.
3. Observe how the app will not automatically sync the new folder.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: Android 11
 - Version 2.1.1

**Additional context**
I have a large amount of albums (300+), but I didn't have any issues with the initial sync after removing the problematic albums/files.

**Comment by scubajeff** [comment]
Please elaborate, I just can't catch what is going on with this issue.

**Comment by MetalNeo** [comment]
I tried adding some new albums today into the Les Pas folder in Nextcloud, but the app will not sync the new folders I added.

I thought something might have been wrong with my new album, so I copied an existing synced album and renamed it. The copied/renamed album also doesn't sync, even though the same images synced without issue before.

**Comment by scubajeff** [comment]
I suspect that there is something wrong happened in the sync process even before you create these new folders.

Try open Les Pas app, it will sync once with server at startup. Then on your server, monitor your  web server's access log, if you are using apache like I do, use the following:
`grep LesPas /var/log/apache2/access.log`
see if you can spot anything wired.

**Comment by MetalNeo** [comment]
Thank you for the advice!

Seems that Les Pas had indexed some albums that I moved out of the folder because they had some problematic files within them. It couldn't find the json file in the album since it was no longer around and thus couldn't continue the sync.

After I placed the albums back (including the json files), all of the new albums synced without issue!

**Comment by scubajeff** [comment]
Could you tell me what do you find out with those problematic files? What exactly went wrong?

**Comment by MetalNeo** [comment]
I was going to create a separate issue for it, but the sync process also seemed to be getting stuck on files that contained illegal characters. Almost all of my .gif files have a space in their name, and some of my pictures with parentheses or brackets also would cause the sync to get hung up.

My temporary solution was to move the folder/pictured out and then move them back either when a fix was available or after renaming them to a filename that the app can handle.

**Comment by scubajeff** [comment]
Could you please just give me an example of what those names are? so that I can reproduce the bug here.

**Comment by MetalNeo** [comment]
`A gif name.gif`
`[something].jpg`
`(test).png`

**Comment by scubajeff** [comment]
just tested here, file name with space, parenthese and bracket all synced properly without any problem. the issue is not with the naming.

**Comment by MetalNeo** [comment]
Very strange. I can't reproduce the issue anymore. I think the issue must have been occurring because of something from the older version of the app. The sync was getting stuck looking for files that I removed manually in Nextcloud, but now it is not getting stuck when I rename/move/delete files manually anymore.

Marking issue as resolved.
