### ISSUE TITLE
Auto-Repeat/Loop GIFs/Videos

### ISSUE THREAD

**Issue by MetalNeo** [scubajeff/lespas#20]
**Is your feature request related to a problem? Please describe.**
I would like a GIF to automatically restart after it plays once, without having to manually play it again.

**Describe the solution you'd like**
I would like to have an option to enable/disable automatic looping of GIFs/videos, preferably enabled by default.

**Describe alternatives you've considered**
Using my phone's built-in gallery to watch GIFs with auto-loop.

**Comment by scubajeff** [comment]
That's a great idea!
