### ISSUE TITLE
File size choice

### ISSUE THREAD

**Issue by Allistakn** [scubajeff/lespas#21]
First of all, thanks for the great app! 

**Is your feature request related to a problem? Please describe.**
It appears that, for example a 2.5 mb / 2700x3600 jpg is reduced to 185 kb / 1200x1600 when passing through LesPas. That could be a problem for people who are not aware of it or who prefer less strong size reduction, as it appears that there is no indication nor option about that.

**Describe the solution you'd like**
Though that actually greatly reduces the storage needs, it would be good to have some choices.

**Describe alternatives you've considered**
Or some clear documentation about how it will be processed ; it is quite silent for now I think. 
At least I didn't find something about that in the description of the app nor in the in-app dialogues. For example, I processed some files without thinking about that, files that I didn't want to have the quality reduced so drastically, and I realized after hand when I checked the fruit of my effort. I think that could cause some frustration.

**Comment by scubajeff** [comment]
Les Pas store and sync file as it is, will NOT compress it. That's why it take up so much storage space, I even have to write a [FAQ](https://github.com/scubajeff/lespas#why-does-les-pas-use-a-lot-of-storage-space) session to explain all this.

**Comment by Allistakn** [comment]
Hi

Thanks for the response. 

Yeah I saw that section so I didn't understand. It means that's it's not les pas who compress the size when I upload ?

I use a stock samsung s20fe. Sharing from the gallery app to a les pas album crop the size a the jpeg drastically. I was thinking it was les pas. Same size on the les pas app, on the nextcloud server.

**Comment by scubajeff** [comment]
To make things clear, you can try sharing picture to les pas using another app, like File management app.
