### ISSUE TITLE
Feature Request: Better Camera Roll Viewing Experience

### ISSUE THREAD

**Issue by theuser18** [scubajeff/lespas#23]
Currently, only being able to view a few photos at a time and having to swipe horizontally makes browsing the Camera Roll difficult. It would be great to have it look more akin to Google Photos.

Thanks for the fantastic app!

**Comment by scubajeff** [comment]
I have degoogle for years now. Does Google Photos need a google account to work?

**Comment by scubajeff** [comment]
try google photos a bit. seems to me the difference is that it use all the screen estate for photo list, is this the better viewing experience? or did I miss something?

**Comment by theuser18** [comment]
> try google photos a bit. seems to me the difference is that it use all the screen estate for photo list, is this the better viewing experience? or did I miss something?

Yes, essentially that is the case. It makes it easier to scroll throug a bunch of stuff and batch delete photos.

**Comment by scubajeff** [comment]
understand. let me see what i can do. batch delete option is nice to have.

**Comment by scubajeff** [comment]
In release 2.3.6, user can swipe up to reveal camera roll list. Actions like delete, share and add to Les Pas can be applied to selected items in this list

**Comment by theuser18** [comment]
> In release 2.3.6, user can swipe up to reveal camera roll list. Actions like delete, share and add to Les Pas can be applied to selected items in this list

It looks great. Though I would personally prefer seeing the camera roll list first by default, not the last photo maximized.

**Comment by scubajeff** [comment]
I'm not totally agree with such UX change, since there must be quite a few people who would like to see the latest shot rather than the list at start. What do you think of an option switch in setting to satisfy both?
