### ISSUE TITLE
Feature Request: Map view of EXIF location

### ISSUE THREAD

**Issue by steviehs** [scubajeff/lespas#30]
For my android gallery I am actually using f-stop, but I'd rather go with LesPas.
One thing which is really nice is the map view of a picture to see, where it was taken. Would be great to have such a thing and may be even better, if not google maps would be used but OsmAnd...

**Comment by scubajeff** [comment]
This is also planned for search function category. I don't want to involve Google location API neither. Studying OSMAndroid, will take time, stay tunned.

**Comment by scubajeff** [comment]
spent some time on several geocoding service providers, restriction of free plan, vague privacy agreement, ...

there is also a way to do this with local database, however, db file size is way too large.

this feature is not gonna be here anytime soon.

**Comment by steviehs** [comment]
wouldn't it "just be easy" to use Osmand's API (https://github.com/osmandapp/osmand-api-demo/tree/master/OsmAnd-api-sample) to open the EXIF's location?

**Comment by scubajeff** [comment]
their server restrict access to 1 query per minute per app

**Comment by steviehs** [comment]
Now I am really confused. I'd thought this API is for sending intents to the local installed Osmand instance? Why is there any server access necessary? At the end this all is a nice to have feature... but from my use case I think no, city level is not something useful... it should be the real location...

**Comment by scubajeff** [comment]
I see. I'm talking about search/group by picture taken location, and what you need is a map view. I will explore Osmand a little bit more, seems like it's a free/premium app which provide an API through android intent.

**Comment by steviehs** [comment]
Ah, now I got the misunderstanding. Yes, I'd say this is a different use case.
Osmand is as Osmand+ completely free on Fdroid. 
I guess F-Stop (which is the Closed Source album I use right now) works in the same way with Google Maps: if I go for the position of the Photo taken, it fires Google Maps with the marked position. In the app overview F-Stop and Maps are both open.

**Comment by scubajeff** [comment]
if that's your case, it would be very easy to implement. all these map app, including goggle map and osmand, listen to the same intent. all i need to do is to add a button launching the map app if coordinate found in exif.

**Comment by eknoes** [comment]
The [Nextcloud Maps](https://github.com/nextcloud/maps) plugin already displays the pictures. Is it somehow possible (maybe also by extending nextcloud maps) to stream / include these results to the phone? Then, Les Pas would not need a large local database of all pictures. It is also quite usable already on the phone via browser, so an easy solution would be including it as a webview (?)

**Comment by scubajeff** [comment]
pretty close to push a new release for all of you map lovers. view photo taking location on map, search by location, and probably show your entire album on map will all be in this release. stay tuned.

**Comment by scubajeff** [comment]
just released 2.4.0 with updates to support location data

**Comment by steviehs** [comment]
thanks a lot! That looks nice!  And the show entire album on the map is really great! Now I will switch over from F-Stop.

just a few remarks (not for complaining, really :-):
may be a sole button for showing it on the map would be nicer?
in portrait mode on my phone the +- buttons are not visible
if you switch to google maps for showing the location in the external map service, it is zoomed in extremely (2m resolution) and no marker at the point is set. F-Stop shows a location at 200m resolution...

**Comment by scubajeff** [comment]
> may be a sole button for showing it on the map would be nicer?
on which screen?

> in portrait mode on my phone the +- buttons are not visible
will investigate, can't reproduce in my testing machine. u can always use pinch to zoom gesture though

> it is zoomed in extremely (2m resolution) 
will fix this in next release

thank you very much for your feedback! stay tuned for a autoplay button when showing entire trip on map.

**Comment by steviehs** [comment]
> 



> > may be a sole button for showing it on the map would be nicer?
> on which screen?

![grafik](https://user-images.githubusercontent.com/26877141/145575380-e5470600-4a0d-40a2-a984-913a587b5800.png)

I would put it on this screen. Either one button more or replace the background pict button?

> > in portrait mode on my phone the +- buttons are not visible
> will investigate, can't reproduce in my testing machine. u can always use pinch to zoom gesture though

![grafik](https://user-images.githubusercontent.com/26877141/145575547-880014c2-eda6-4652-bd58-62791deb512a.png)

haha, have not tried the zoom gesture, yes, it works.

> thank you very much for your feedback! stay tuned for a autoplay button when showing entire trip on map.

wow, this sounds like a nice idea!

Thanks for your prompt replies!

**Comment by scubajeff** [comment]
pretty amazing picture there.

**Comment by steviehs** [comment]
I had to choose one with a nice location :-)

**Comment by scubajeff** [comment]
just updated my code this afternoon which will retrieve a 35mm equivelant focal point data from EXIF if there is such a tag exists, so that we can get rid of the 1mm noncence.

**Comment by scubajeff** [comment]
i know why you can't see the zoom button. when in landscape mode, there is not enough vertical space to show all the meta data including the map, you have to scroll the content to the bottom of the dialog, however if you start scroll gesture from the map, it will scroll the map instead, you have to scroll outside the map. nested scroll views is a headache
