### ISSUE TITLE
Allow Searching/Filtering by Name of Folder/File

### ISSUE THREAD

**Issue by MetalNeo** [scubajeff/lespas#31]
**Is your feature request related to a problem? Please describe.**
I have a large amount of folders and pictures and sometimes I spend a lot of time scrolling through the lists looking for them.

**Describe the solution you'd like**
I would like to have the option to filter and/or search folders and images to make it easier to access a folder or image more quickly.

**Describe alternatives you've considered**
Manually scrolling through the folders and pictures.

**Comment by scubajeff** [comment]
filter albums? filter photos? by what? name? date?

**Comment by scubajeff** [comment]
sorting for album (e.g. folder) function will be in next release. filtering is lacking for both album and photo, however, you might already notice, when you scroll the photo list, a yellow sticker hinting the date (or the initial of filename if you sort the list by name) will show briefly
