### ISSUE TITLE
Netzwerkfehler (Network error)

### ISSUE THREAD

**Issue by tkirchm** [scubajeff/lespas#34]
I loaded Les Pas from FDroid yesterday and can't login to my Nextcloud. 

My NextcloudPi 21.0.4.1 runns in my local network.

When entering my ip adress it only say's "Netzwerkfehler, versuchen Sie es erneut" (Network error, try again.) doesn't matter if i use http or https.

Same message on Samsung and Huawei Phone. IP adress is working from phone browser.

What am I doing wrong?

**Comment by scubajeff** [comment]
Are you using http connection? If yes, this is a known bug and was fixed in release 2.3.10.

**Comment by baixiang-main** [comment]
> Are you using http connection? If yes, this is a known bug and was fixed in release 2.3.10.

I am still experiencing this problem despite being in version 2.3.10. It perpetually prompts a network error in my one plus Phone. I hope this bug is fixed, I'm really looking forward to using this app.

**Comment by scubajeff** [comment]
@baixiang-main r u using http connection?

**Comment by tkirchm** [comment]
It worked with a self signed certificate via https. But on a different nc with no certificate it is showing me the login screen in version 2.3.10 but it nc never does the login. 
I connect directly with ip adress.

**Comment by scubajeff** [comment]
no certificate means http only, right? what is the output of this command:
`curl -k -X GET 'http://your_nextcloud_server_address/ocs/v2.php/cloud/capabilities?format=json' -H "OCS-APIRequest: true"`

**Comment by tkirchm** [comment]
Sorry for the late answer:
CS-APIRequest: true"
curl: (6) Could not resolve host: your_nextcloud_server_address

**Comment by tkirchm** [comment]
Yes. No certificate means http.

**Comment by scubajeff** [comment]
@tkirchm please replace 'your_nextcloud_server_address' with your server's address, and try again.

**Comment by tkirchm** [comment]
Sorry:
{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"version":{"major":21,"minor":0,"micro":4,"string":"21.0.4","edition":"","extendedSupport":false},"capabilities":{"bruteforce":{"delay":0},"theming":{"name":"NextCloudPi","url":"https:\/\/ownyourbits.com","slogan":"keep your data close","color":"#0082c9","color-text":"#ffffff","color-element":"#0082c9","color-element-bright":"#0082c9","color-element-dark":"#0082c9","logo":"https:\/\/192.168.0.10\/index.php\/apps\/theming\/image\/logo?v=0&useSvg=1","background":"https:\/\/192.168.0.10\/index.php\/apps\/theming\/image\/background?v=0","background-plain":false,"background-default":false,"logoheader":"https:\/\/192.168.0.10\/index.php\/apps\/theming\/image\/logo?v=0&useSvg=1","favicon":"https:\/\/192.168.0.10\/index.php\/apps\/theming\/image\/logo?v=0&useSvg=1"}}}}}

**Comment by scubajeff** [comment]
all the web address shown here are https based, are you sure you are using http only?

**Comment by scubajeff** [comment]
what is the address you typed in Les Pas's login page?` https://192.168.0.10/index.php` or `https://192.168.0.10`?

**Comment by tkirchm** [comment]
I just disabled force https on my nextcloudpi.
I used 192.168.0.10 .
Nextcloud login screen apears and I can use my credentials but after login nothing happens.

**Comment by scubajeff** [comment]
so is login successful? what do you mean by nothing happen?

**Comment by tkirchm** [comment]
![signal-2021-11-12-204546_001](https://user-images.githubusercontent.com/58719851/141526478-a5914a97-0ad8-4278-b558-88aaf3a16c02.jpeg)
Nothing happens after entering login information.

**Comment by scubajeff** [comment]
after login page appears, actual login process is totally controlled by nextcloud server, so i think this probably is a server miss config, i suggest you check your web server's access log, might find out some hints there

**Comment by J4gQBqqR** [comment]
I have this problem with 2.3.13 as well. I cannot login to Nextcloud, permanently stack in the login screen.
I use https signed by Letsencrypt and my other Nextcloud app works fine, e.g. DavX5

**Comment by scubajeff** [comment]
@J4gQBqqR stuck means that waiting sign spins forever or something else? did you see any error message or screen？

**Comment by J4gQBqqR** [comment]
There is no wait sign spinning. The behavior is like, "I clicked the login using app token button, but nothing happens". I can see my internet speed meter shows around 20 kB/s data exchange for a second or two. But nothing changed on my screen.
It might be because I enabled 2FA on my account, and Nextcloud detect that my phone has the Nextcloud app installed, so it refuses me to sign in unless I use Single Sign On (SSO) flow.

**Comment by scubajeff** [comment]
les pas uses nextcloud login flow api, all you need is to key in your NS server address url in the login page and les pas will bring up Nextcloud's authentication page, i guess you can use your 2FA on that page

**Comment by J4gQBqqR** [comment]
Thank you for your explanation. I am not sure if using 2FA is an optimal method since the sign in cookie expires? But anyway, I tried to use 2FA. Here is the result:
![Screenshot_20211207-140908_Lawnchair](https://user-images.githubusercontent.com/77554817/145091055-66160aa8-d4ac-4c5e-bbae-560890b137d3.png)

I am stacked forever in the above screenshot.

Just like the app passcode that I am trying to use, nothing happens after I click on the button. It seems to me that Les Pas is not detecting that I am authorizing the signing in.

It could be a problem because of 2FA?

**Comment by scubajeff** [comment]
after u press that button, NC server should return the app key to Les Pas, it should be a simple url with a special scheme. not sure what went wrong here. i'll set up my test environment to debug this issue. mind told me what 2FA method r u using? btw, i'm busy cracking the map feature right now, might take a while for this to be solved.

**Comment by J4gQBqqR** [comment]
I am using email, TOTP, Nextcloud push notifications. The one that I tested is the TOTP one. I also tested the one-time App Passcode.

**Comment by scubajeff** [comment]
will explore Nextcloud's login flow v2, seems to me it will solve the 2FA problem.

**Comment by J4gQBqqR** [comment]
Thank you for your excellent support. Looking forward to it.

**Comment by scubajeff** [comment]
I enable TOTP today on my server, I use andOTP to generate code on my phone,  I can login perfectly fine with no change to Les Pas's code.  What am I missing here?

**Comment by J4gQBqqR** [comment]
Not really sure. The version I used is the F-droid version.

Is there anything further I can do to help you debug?

**Comment by J4gQBqqR** [comment]
To verify my app passcode is working correctly, I tested it with another app:
https://www.f-droid.org/packages/com.polar.nextcloudservices/

This app logs in (using app passcode) and pulls notifications correctly from server. Not sure what is the difference here.

**Comment by J4gQBqqR** [comment]
Setting -> security -> Devices & sessions -> scroll down to bottom -> create new app password

**Comment by scubajeff** [comment]
so that's App Password. it's not 2FA. i'll take a look.

**Comment by J4gQBqqR** [comment]
But what's wired is, I tried 2FA using TOTP, I can proceed all the way to the grant access screen and was stucked like this:
https://github.com/scubajeff/lespas/issues/34#issuecomment-993528726

**Comment by scubajeff** [comment]
all the authentication stuffs are handled by nextcloud server, they do the heavy lifting and return an app password to client app like les pas, by using a special scheme url string. if it stop at the authentication screen, i guess something must went wrong on server side, would you please take a look at nextcloud's log or http server log?

**Comment by J4gQBqqR** [comment]
I did not see error in the log:
```
{"reqId":"hXjeDY5sVWfB7xUUUNvF","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"apporder","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"hXjeDY5sVWfB7xUUUNvF","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"camerarawpreviews","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"hXjeDY5sVWfB7xUUUNvF","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"serverDI","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"The requested alias \"PreviewManager\" is deprecated. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"hXjeDY5sVWfB7xUUUNvF","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"drawio","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"hXjeDY5sVWfB7xUUUNvF","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"extract","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"hXjeDY5sVWfB7xUUUNvF","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"files_sharing","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"hXjeDY5sVWfB7xUUUNvF","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"maps","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"aIsbSWEsF2UCLaRFCgTB","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"apporder","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"aIsbSWEsF2UCLaRFCgTB","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"camerarawpreviews","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"aIsbSWEsF2UCLaRFCgTB","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"serverDI","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"The requested alias \"PreviewManager\" is deprecated. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"aIsbSWEsF2UCLaRFCgTB","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"drawio","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"aIsbSWEsF2UCLaRFCgTB","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"extract","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"aIsbSWEsF2UCLaRFCgTB","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"files_sharing","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"aIsbSWEsF2UCLaRFCgTB","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"maps","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"lxZB49IaxRFaTDZ5mdih","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"apporder","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"lxZB49IaxRFaTDZ5mdih","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"camerarawpreviews","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"lxZB49IaxRFaTDZ5mdih","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"serverDI","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"The requested alias \"PreviewManager\" is deprecated. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"lxZB49IaxRFaTDZ5mdih","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"drawio","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"lxZB49IaxRFaTDZ5mdih","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"extract","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"lxZB49IaxRFaTDZ5mdih","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"files_sharing","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
{"reqId":"lxZB49IaxRFaTDZ5mdih","level":0,"time":"2021-12-15T01:11:41+00:00","remoteAddr":"172.18.0.2","user":"masked","app":"maps","method":"GET","url":"/index.php/apps/theming/favicon?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Les Pas on oneplus_gm1917","version":"22.2.3.0"}
```

**Comment by J4gQBqqR** [comment]
I eventually managed to login my next loud instance successfully.

This is done by adding `'overwriteprotocol' => 'https'` to the next loud config.php.

Please close the issue if you think this issue is not relevant anymore.
