### ISSUE TITLE
Hidden Files/Folders Support

### ISSUE THREAD

**Issue by MetalNeo** [scubajeff/lespas#35]
**Is your feature request related to a problem? Please describe.**
I have some albums/images that I would not like to see by default. Typically, I would place a . in front of the file so that it is hidden, but this behavior is not present in Les Pas.

**Describe the solution you'd like**
Provide a toggle to choose if files/folders that start with a ., such as ".image.jpg", should be hidden. A way to mark/unmark a folder/image as hidden in-app by adding or removing a . in front of it would also be nice.

**Describe alternatives you've considered**
Placing images outside of Les Pas and moving them in either manually or through scripts when I want to view the images.

**Comment by scubajeff** [comment]
can i describe this as honor the hiden files and folders on Linux?

**Comment by MetalNeo** [comment]
Yes, that would be an accurate description.
