### ISSUE TITLE
Creating album from Camera Roll or from other App keeps stuck forever, uploading from file picker works normally

### ISSUE THREAD

**Issue by brennoflavio** [scubajeff/lespas#36]
First of all, thanks for the app! Really loving the experience. If my bug description was not good enough, I can record a video of what is happening on my device.

**Describe the bug**
When I open the Camera Roll in the app, select a photo, touch the icon to create a new album, and create a new album, the app got stuck in the dialog that the image is being processed. This also happens when I'm in the Camera Roll and try to add the photo to an existing album.

This does not happen when I'm in the file picker UI. For example, when I'm inside an album and select the icon to add a new photo, it opens the File Picker. If I select a photo there, it works normally.

**To Reproduce**
1. Go to Camera Roll
2. Pick a photo
3. Click on Les Pas logo
4. In the modal, select an album (or go to the bottom an create a new album)
5. See that the app never uploads the photo to the album

**Expected behavior**
After some time, the dialog "Need to upload x kb to the server..." should appear, as it happens when I select from the file picker UI

**Screenshots**
This is the screen with app got stuck. I've applied blur to the photo.

![Screenshot_20211225-124123_Les_Pas](https://user-images.githubusercontent.com/27819187/147388614-f20c6903-7608-4cfe-9d86-11199c4edfa4.png)

**Smartphone (please complete the following information):**
 - Device: Pocophone F1
 - OS: Lineage OS 11, [MicroG Build](https://lineage.microg.org)
 - Version 11
 - Les Pas Version: v2.4.1, from F-Droid

**Additional context**
Few weeks ago, this was not a problem, as I was able to create and upload albums normally. I didn't find a way to retrieve logs from the application, but if its possible I can provide.

**Comment by scubajeff** [comment]
Thank you for using my app. Your description is just fine. The latest release 2.4.3, which was pushed to fdroid for building 4 days ago, fixed several bugs of reading EXIF data. Please update to this version when it's available and see if it fixes this bug.

Happy X'mas!

**Comment by brennoflavio** [comment]
Thanks for the reply. As soon as F-Droid release the new version I'll test and come back with the result. Merry Christmas!

**Comment by fcwoknhenuxdfiyv** [comment]
Hi! I have the same problem and 2.4.3 doesn't fix it. Is there a way of finding you some useful debugging information?

**Comment by scubajeff** [comment]
@fcwoknhenuxdfiyv you can send me the picture file if that's ok with you. scubajeffrey@criptext.com

**Comment by scubajeff** [comment]
@fcwoknhenuxdfiyv Is it just one particular file or every one of them in camera roll?

**Comment by brennoflavio** [comment]
@scubajeff I just updated and tested the photo upload, and the problem persists here. For me, it happens on every file, I selected some random ones and all of them got stuck. Selecting one or multiple files does not seems to help either.

**Comment by scubajeff** [comment]
Found it, from release 2.4, Les Pas started processing photo's GPS meta data from EXIF. Seems like some devices, or custom ROMs required app requesting ACCESS_MEDIA_LOCATION permission explicily, some doesn't, like the emulator and some other ROMs like my own phone running a variant of Android 11 DotOS . This bug also breaks viewing camera roll photo's detail information fuction and camera roll auto backup too, and maybe some other places. Fix is on the way.

**Comment by scubajeff** [comment]
@brennoflavio @fcwoknhenuxdfiyv 
Meanwhile, if you have some time to spare, please help me with this: snap a picture which contain GPS location information, then add this picture to Les Pas thru file picker UI, see if you can see the map displayed when you view this picture's detail info in Les Pas.

**Comment by fcwoknhenuxdfiyv** [comment]
I just took a picture and there is no location data in the details popup. I'm using /e/os which I believe is still on Android 10 - I'll verify later as the battery just died.

Thanks for all your help!

**Comment by brennoflavio** [comment]
@scubajeff Just did it and the map renders correctly for me (Its blank in the screenshot but it rendered few seconds later)

![Screenshot_20211227-182213_Les_Pas](https://user-images.githubusercontent.com/27819187/147508162-89541c4d-9091-450a-9597-19f1cd272c07.png)

**Comment by brennoflavio** [comment]
Also I can confirm that touching the "details" button in any photo of the camera roll crashes the app.

**Comment by scubajeff** [comment]
@brennoflavio could you please do one last test: goto search screen -> toggle search in camera roll on Toolbar -> select search location -> no matter what result turns out, leave search screen, and everything should be ok now

**Comment by brennoflavio** [comment]
Just tested it, and yep, it fixes the bug. Thanks!

**Comment by scubajeff** [comment]
that's a work around, actual fix is still on the way

**Comment by scubajeff** [comment]
Release 2.4.4 should fix this. It's live now on Google Play

**Comment by brennoflavio** [comment]
Yep, that's what I meant to say. I'll test with a fresh installation in a Shelter profile as soon as the update is released on f-droid

**Comment by scubajeff** [comment]
thank you very much.

**Comment by brennoflavio** [comment]
Just tested a fresh install from a shelter profile, and can confirm that it work as intended now. I think we van close the issue now

**Comment by scubajeff** [comment]
thank you!
