### ISSUE TITLE
Opening Albums Twice Occasionally Crashes the App

### ISSUE THREAD

**Issue by MetalNeo** [scubajeff/lespas#37]
**Describe the bug**
I am not sure why, but Les Pas has recently started to crash when I'm trying to open albums.

**To Reproduce**
1. Open an album.
2. Go back to the main screen.
3. Open the same album (or another album).
4. App crashes.

**Expected behavior**
App should not crash.

**Smartphone (please complete the following information):**
 - Device: Pixel 5A
 - OS: Android 12
 - Version 2.4.4

**Additional context**
I have tried deleting the json data from my Nextcloud and tried reinstalling the app, but the issue persists. The odd thing is that only certain albums appear to trigger this behavior, not all of them.

**Comment by scubajeff** [comment]
Almost all the recent changes and fixes are about acquiring EXIF reading permission. Will review each patch. Since it happens only to some of the albums, if you can manage to find the pattern, that will certainly help a lot.

**Comment by MetalNeo** [comment]
Actually, all of the albums appear to be crashing when opened twice. I can't find any that aren't exhibiting the behavior anymore. I will try and downgrade my version through Fdroid to see if I can replicate the issue on previous versions as well.

**Comment by scubajeff** [comment]
I can't reproduce this on my side.

**Comment by MetalNeo** [comment]
Decided to temporarily move all of my pictures and use just one album with one image.
Album name: 2american4you
Image name: America number one.jpg

Still having the issue. I am able to reproduce the issue on versions 2.4.4 and 2.4.1. I also updated my Nextcloud server to the latest Stable release (23.0.0). If you would like me to provide a copy of the image for testing, I can do that too.

**Comment by scubajeff** [comment]
Please send it to scubajeffrey@criptext.com

**Comment by scubajeff** [comment]
Unfortunately, with the image file you sent to me, I still can't reproduce this bug. But I found another issue, might be related to this one. If you rotate device on Album Detail screen, app will crash sometimes due to "show in map" menu item initialization error, this menu item was introduced in 2.4.x

**Comment by MetalNeo** [comment]
I installed v2.4.5 today and the issue seems to be resolved now! Thanks for the help!
