### ISSUE TITLE
Import nextcloud photos

### ISSUE THREAD

**Issue by sttrebo** [scubajeff/lespas#39]
I've got abot 30gb of photos already in nextcloud.  Is there a way to import them into les pas?

**Comment by scubajeff** [comment]
First of all, you should note that Les Pas is built to be an album/gallery app on Android, not a auto tagger/categorizer. The suggested use case would be like this: screen and select some of your best shots from your 30G collection, organize them into meaningful folders, and import them into Les Pas. I personally has about 14GB in Les Pas and it's growing. Though please be reminded that Les Pas store a copy of all the photos in your phone's storage, make sure you have enough space before you start and also give it some time for it to finish the first sync.

As for the actual importing, make a folder named "lespas" in your Nextcloud user's home folder and put thosed organized folders into it. Start Les Pas app on your phone and it will start syncing. If you already stored photos in somewhere else, you can simply symlink them into "lespas".
