### ISSUE TITLE
infinitely attempting to connect with nextcloud kdrive

### ISSUE THREAD

**Issue by pokyah** [scubajeff/lespas#45]
Hello,

When I try to connect to my kdrive ( which is a managed nextcloud instance) using  connect.drive.infomaniak.com (as mentioned in https://www.infomaniak.com/en/support/faq/2409/kdrive-logging-in-to-your-drive-via-webdav) on the les pas first login screen, les pas infinitely attempts to connect and nothing happens (no error message).

I would expect that les pas would connect or throw me an error explaining why I can't connect

![Screenshot_2022-02-13-12-15-57-136_site leos apps lespas](https://user-images.githubusercontent.com/15193683/153750545-8ec8653a-7376-4bac-9367-bf1ceb15b744.jpg)

Here is my phone config :

![Screenshot_2022-02-13-12-17-00-760_com android settings](https://user-images.githubusercontent.com/15193683/153750635-1e0bd64d-35ba-432b-a8ad-382244cc05b6.jpg)

I also want to let you know that the official nextcloud app can connect to my kdrive without any trouble.

Thanks for your help

**Comment by scubajeff** [comment]
Login to your Nextcloud instance in web browser, select Settings->Mobile & desktop, scroll to the bottom, copy the address listed in 'Server address' section and use this address with Les Pas.

**Comment by pokyah** [comment]
The thing is that kdrive is kind of a fork of nextcloud rather than a pure managed instance. So I can't check what you have proposed.

However, on my android phone I can connect to my kdrive using the official nextcloud app.

If I click on manage accounts in the android nextcloud app, I can see the following working connection :

Username@email.com@102960.connect.drive.infomaniak.com (where username@email.com is actually replaced by my true email used as login credential).

I've tried this and also : 

102960.connect.drive.infomaniak.com connect.drive.infomaniak.com 

But with no difference.

How can we debug this?

**Comment by scubajeff** [comment]
to authenticate lespas to your nextcloud server, it use [nextcloud ocs login flow](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html), please ask kdrive staff if they support this.

**Comment by scubajeff** [comment]
further study on kdrive website, confirm they use different login mechanism which Les Pas doesn't support at this moment.

**Comment by pokyah** [comment]
Hi @scubajeff, finally got an answer from Kdrive. They told me Kdrive is not based on nextcloud anymore...

**Comment by ThomasDeschler** [comment]
Hello @scubajeff,

Thank you for your update.
I tried to connect using https://connect.drive.infomaniak.com/ with the release 2.5.5.
I can reach the page and can login to Infomaniak, but after that the app crashes.
When I try to reopen the app it crashes every time.

My phone: Pixel 4a 5G with Android 12

**Comment by scubajeff** [comment]
this sounds quite similar to #54

**Comment by ThomasDeschler** [comment]
I have sent the crash log by email.

**Comment by scubajeff** [comment]
@ThomasDeschler, the mail you sent to me didn't have log attached. Tried sending you mail, but had been rejected by your mail server's spam filter.

**Comment by ThomasDeschler** [comment]
Noted, I have sent a link to download the crash log. I hope this method works.

**Comment by ThomasDeschler** [comment]
No more opening crashes with this version.
Thank you!

**Comment by scubajeff** [comment]
from the log, i see some other exceptions too. seems like there are restrictions been applied to your kdrive's home folder. can you create new album?

**Comment by pokyah** [comment]
> Just release 2.5.5. With this version, I seems to be able to reach the login page of connect.drive.infomaniak.com. You can give it a try.

Wow ! Excellent ! Will try it today

**Comment by pokyah** [comment]
Sadly I can't connect as I got stuck by a bugged Infomaniak page that propose me to choose between one of my drives.

The intefarce is bugged and it's impossible to select a drive. I'll send thema ticket to make things work and  will come back to LesPas.

Will keep you updated

**Comment by pokyah** [comment]
Hi @scubajeff !
Thanks for continuing developing Les Pas. I want to try it again. I'm currently using version 2.9.6 but still can't figure out how to connect to kdrive. Could you show me which URL you use to connect?

Thanks

**Comment by scubajeff** [comment]
According to this link https://www.infomaniak.com/en/support/faq/2409/connect-to-kdrive-via-webdav
kDrive is different from Nextcloud in terms of API endpoint and folder structure. Extra works needed to support it. Will evaluate the possibility later.

**Comment by scubajeff** [comment]
@pokyah not at all. eventually it's the way to more user installation.

**Comment by scubajeff** [comment]
@pokyah Seems like infomanic blocked me from creating kdrive. Unless you could help me setup a kdrive account for testing, I can't do anything.
