### ISSUE TITLE
Buttons in Camera Rolle have no function

### ISSUE THREAD

**Issue by weinic** [scubajeff/lespas#49]
See The Screenshot below

![Screenshot_20220325-070521__01](https://user-images.githubusercontent.com/57099502/160064773-fdb7c76b-8668-4e3c-9d45-512c8630331e.jpg)

Android App Version 2.5.3

**Comment by scubajeff** [comment]
long press on list items you want to work on, then the buttons will be activated.

**Comment by weinic** [comment]
No, that is just not the case.
Even a long press on an entry only turns the keys black, but they still don't work.

What function should the left button have?
It's black, but it doesn't work either.
For my understanding it should close the overview list again.

**Comment by scubajeff** [comment]
Re-produced this bug on development machine. It's related to recent change on action bar management. When bottom sheet is fully expanded, the function button area on the top is actually cover by a transparent action bar, they are not responding to clicks.

**Comment by scubajeff** [comment]
fix is on the way

**Comment by weinic** [comment]
Ok cool 
then I am curious 👍
