### ISSUE TITLE
Can't sync Photos

### ISSUE THREAD

**Issue by galaxyrun** [scubajeff/lespas#5]
**Describe the bug**
I can't sync my Photos with nextcloud. When i create a folder on my phone (lespas app) it will show up in my lespas folder. The already existing folders will not show up in the app.

**OS**
 - Nextcloud 20.0.4
 - Lespas 1.3
 - PHP 7.3.19
 - mysql 10.3.27
 - NextCloudPi version v1.34.1

***Error message 1***

[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: Could not open file at <<closure>>

0. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 90
   OCA\DAV\Connector\Sabre\File->get()
1. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
2. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
   Sabre\DAV\Server->emit("method:GET", [Sabre\HTTP\Requ ... }])
3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
   Sabre\DAV\Server->start()
5. /var/www/nextcloud/apps/dav/lib/Server.php line 332
   Sabre\DAV\Server->exec()
6. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
7. /var/www/nextcloud/remote.php line 167
   require_once("/var/www/nextcl ... p")

***Error message 2***

[PHP] Error: Error: fopen(/media/1d39d588-0b92-6a47-bc86-0b4da013189a/ncdata/USERNAME/files/lespas/Photos from 2012/CAM00064.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#355 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "fopen(/media/1d ... y", "/var/www/nextcl ... p", 355, {path: "files/le ... "})
 1. /var/www/nextcloud/lib/private/Files/Storage/Local.php line 355
    fopen("/media/1d39d588 ... g", "r")
 2. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 300
    OC\Files\Storage\Local->fopen("files/lespas/Ph ... g", "r")
 3. /var/www/nextcloud/lib/private/Files/View.php line 1165
    OC\Files\Storage\Wrapper\Wrapper->fopen("files/lespas/Ph ... g", "r")
 4. /var/www/nextcloud/lib/private/Files/View.php line 1001
    OC\Files\View->basicOperation("fopen", "/lespas/Photos from 2012/CAM00064.jpg", ["read"], "r")
 5. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 434
    OC\Files\View->fopen("lespas/Photos from 2012/CAM00064.jpg", "r")
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 90
    OCA\DAV\Connector\Sabre\File->get()
 7. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
 8. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:GET", [Sabre\HTTP\Requ ... }])
 9. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
10. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
11. /var/www/nextcloud/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
12. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
13. /var/www/nextcloud/remote.php line 167
    require_once("/var/www/nextcl ... p")

GET /remote.php/dav/files/USERNAME/lespas/Photos%20from%202012/CAM00064.jpg

**Comment by scubajeff** [comment]
Are these log messages from your nextcloud server log?

**Comment by scubajeff** [comment]
Seems to me this is a Nextcloud server setup issue.
