### ISSUE TITLE
LesPas is not syncing remote albums

### ISSUE THREAD

**Issue by brennoflavio** [scubajeff/lespas#50]
**Describe the bug**
Today I installed latest LesPas v2.5.3, Fdroid, in another phone that I have here (Samsung Galaxy M20 with LineageOS). I noticed that no albums were synced from my remote Nextcloud Server. Usually in previous versions it downloaded all my photos from lespas folder into my device.

So I ran two tests: I created a two albums with one photo each, one with the "remote album" toggled in, and another one without it. It created two folders in Nextcloud, and uploaded the photo there. Then I uninstalled and reinstalled the app, and after authenticating, no albums shows in the screen (I waited around 10 hours to report this issue, sync enabled).

I don't have the Preview Generator installed in my server yet due to storage constraints. But in previous versions 
(pre 2.5.0) it downloaded my photos without this requirement

**To Reproduce**
1. Install LesPas from F-droid
2. Login into Nextcloud account
3. Create an Album
4. Check that folder is create remotely
5. Uninstall and Reinstall LesPas, authenticate again
6. Check that album does not show in the UI anymore

**Expected behavior**
In previous versions, albums should download into device. From what I read from the Readme, now should it show as remote albums?

**Screenshots**
LesPas:
![Screenshot_20220327-004538_Les_Pas](https://user-images.githubusercontent.com/27819187/160266054-d6a33f28-f158-40fe-a655-95504b36bd35.png)

Remote Server:
![image](https://user-images.githubusercontent.com/27819187/160266067-4584b502-0721-4498-9114-09c47e6579de.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy M20
 - OS: LineageOS Microg 2022-03-19
 - Version LesPas 2.5.3

**Comment by scubajeff** [comment]
In latest release, after reinstall, all album is downloaded from server and set as "Remote". If you created those album using the latest release, two json file will be created on server in album's folder, Les Pas will validate those json file and try to sync this meta info only when it recreate album record in your phone. So could you please check if json file is created in your server for both your old and new albums?

**Comment by scubajeff** [comment]
If you see only 1 json file in the album folder, then this is a bug also reported from another user yesterday.

**Comment by brennoflavio** [comment]
I just created a new album to find out that no json was created:
![Screenshot_20220327-111958_Nextcloud](https://user-images.githubusercontent.com/27819187/160286161-f65780e4-feb0-482c-bfe1-fbdb8e226414.png)
![Screenshot_20220327-112047_Les_Pas](https://user-images.githubusercontent.com/27819187/160286163-087cb0b1-dba6-49ca-98c5-c9efc725bc10.png)

Old albums always has 2 jsons inside it:

![Screenshot_20220327-112025_Nextcloud](https://user-images.githubusercontent.com/27819187/160286241-3490771f-5f94-4500-8fd3-e7c4365c97ee.png)

**Comment by scubajeff** [comment]
to make sure json file always has the latest meta data of an album, all json files update will happen at the end of the sync process, e.g. after changes from local and remote got synced on both side. that's why there are no json file in the newly created folder because something happens while syncing those old ones. if you would like to help debugging, we can study those json files in the old folders 1x1. if not, that is fine, all you have to do is to remove each and every json files on the server, the sync should start, only catch is album covers information are lost.

**Comment by scubajeff** [comment]
by the way, just found out that you have a hugh collection of photos, so the first sync will take some time to finish

**Comment by brennoflavio** [comment]
I want to help debugging and fixing the issue if it exists!

I have around 7.7GB of photos (26 albums) in lespas folder.

The test album I created had no JSON after ~24 hours of its creation:

![image](https://user-images.githubusercontent.com/27819187/160420163-4399b9fb-0601-4d55-9fcc-339b1f4b3d94.png)

While writing this comment, I uploaded a photo to the album trough Nextcloud web UI, to see if it shows in lespas. Now LesPas shows 3 photos, while remote has 4 photos (But that's pretty recent, I'll wait more to see if it shows):

![image](https://user-images.githubusercontent.com/27819187/160421557-768434cf-2891-4299-89b3-39f590680b03.png)
 
![Screenshot_20220328-113113_Les_Pas](https://user-images.githubusercontent.com/27819187/160421623-eb867c10-8f53-459d-a9d9-c625ec3d08db.png)

About studying JSONs from old albums, what would you suggest? I took two from an album with 10 photos, and they seem pretty standard, describing metadata about the photos and the album itself:

```json
{"lespas":{"photos":[{"id":"135425","name":"IMG-20220211-WA0004.jpg","stime":1644620361,"mime":"image/jpeg","width":1201,"height":1600},{"id":"7548","name":"IMG_20210917_132729.jpg","stime":1631896049,"mime":"image/jpeg","width":3024,"height":4032},{"id":"7561","name":"IMG_20210922_193542.jpg","stime":1632350142,"mime":"image/jpeg","width":3024,"height":4032},{"id":"8513","name":"IMG_20211101_193422.jpg","stime":1635806062,"mime":"image/jpeg","width":3024,"height":4032},{"id":"52395","name":"IMG_20211210_211439.jpg","stime":1639181679,"mime":"image/jpeg","width":1940,"height":2592},{"id":"52405","name":"IMG_20211210_211442.jpg","stime":1639181682,"mime":"image/jpeg","width":1940,"height":2592},{"id":"52476","name":"IMG_20211211_001430.jpg","stime":1639192470,"mime":"image/jpeg","width":4032,"height":3024},{"id":"138427","name":"IMG-20220218-WA0040.jpg","stime":1645274435,"mime":"image/jpeg","width":1247,"height":1280}]}}
```

```json
{"lespas":{"cover":{"id":"135425","filename":"IMG-20220211-WA0004.jpg","baseline":543,"width":1201,"height":1600},"sort":0}}
```

![image](https://user-images.githubusercontent.com/27819187/160422882-00716e86-95b7-4188-b941-068fb0c2229f.png)

**Comment by scubajeff** [comment]
just release 2.5.4, could you please try it?

**Comment by brennoflavio** [comment]
Just updated it, and it works! Legacy album were synced as remote albums, which is great. I tested uploading new photos from both lespas and Nextcloud UI and it worked both ways. Camera roll backup worked as expected too.

Thanks for the awesome app and help.

By the way, I'm thinking on getting into mobile development (I'm a backend go/python developer). Do you have any tips to get started? 

Thanks!

**Comment by scubajeff** [comment]
i started by reading Google's documents. comparing to other companies' works, ithey are well organized and very helpful. the most important thing imho would be the understanding of android apps architecture. googler is running a series on this topic on their youtube channel now, it's a good start.

**Comment by brennoflavio** [comment]
Thanks for the tips!

**Comment by scubajeff** [comment]
btw, you mentioned that you are not using preview generator. how's the picture loading feel? is it fast enough? wondering whether without preview is really a thing.

**Comment by brennoflavio** [comment]
I run a Nextcloud in my  home network (Raspberry Pi 4) with a UDP encrypted tunnel to a VPS that exposes it to the internet. Here is when loading an Album with 13 images:
 
https://user-images.githubusercontent.com/27819187/160670357-923073ce-ab9b-4bb2-8420-4d711e8285f4.mp4

For me that's fine. I noticed that performance degrades as number of photos increase. Like, it takes longer to render each photo. This happens with Nextcloud UI too.

Unfortunately last time I tried to setup previews it took all my space in the SD card, so I'm looking in the future to buy dedicated storage to get this going in my server.

**Comment by scubajeff** [comment]
when generating preview on nextcloud, one have to specify the exact dimension needed, and the api for accessing preview also have to specify exactly the same dimension value. so it's hard to change the setting without affecting the current installations.

**Comment by brennoflavio** [comment]
Thanks for the clarification. If you need any help on debugging, let me know
