### ISSUE TITLE
Q: How to set "Remote" or "Local" Album

### ISSUE THREAD

**Issue by steviehs** [scubajeff/lespas#51]
In the Readme there is mentioned to set an Album as Remote (with the preview generation) and Local.

Right now I am using Les Pas by generating a flatted folder structure with all my pictures reduced to FHD size in a lespas folder. This works fine and fast.  The pros and cons of flat vs. nested folders have been discussed already, so I am fine with these :-)

This was the usual flow so far and I guess this is called "Local"?

Now I would like to understand: how to set a folder to "Remote"?

**Comment by scubajeff** [comment]
in album list screen, long press albums to select them, then click action menu to toggle

**Comment by steviehs** [comment]
Ah got it. So, this is new since 2.5.*? Is there a way to have all folders synced to local by default? klicking on my 360 folders is not that much fun :) touching a file in each folder would also be fine...

**Comment by scubajeff** [comment]
albums sync from server will default to 'remote'. Never thought that there would be a use case of so many albums. Should have a 'select all' action menu item like the one when selecting photos.

**Comment by steviehs** [comment]
even easier for my workflow would be some marker files in the folder e.g. .lp_local  (lespas store locally). 
My workflow is, that I convert _all_ my pictures on my desktop PC to flat folder hierarchy and resize them to FHD. In the same way I could then also add this flag and most probably could also use an API in Nextcloud to share a folder with my family... As soon as this works nicely, I will publish this script...

**Comment by steviehs** [comment]
Hmm.. I see. Maybe it could still be a feature wish, to have a .lp_local file,  which switches from default "remote" to default "local" for all devices on first seen of a folder :-)
I will rework my script to make it useable for others and will share it soon.

**Comment by steviehs** [comment]
Ok, I took my time to rewrite the script to support Nextcloud shares and Les Pas.
If anybody is interested in:
https://gitlab.com/steviehs/stevemisc

So as a result of this: it would be really great to have either the possibility with a kind of a flag per folder like .lp_local to mark that a folder should be really downloaded by Les Pas. Or - maybe even easier - a global switch in Les Pas, how to act on every new folder found?

And once again: thx for Les Pas! It is really a good tool for me!

**Comment by scubajeff** [comment]
A global flag of "default to local/remote" is planned. But before that, I have to finish the feature of 'Backup/Restore preference on server' first. Otherwise, any preference can not be saved across app re-install.

I will update Les Pas's README page to include links to your fantastic script, I'm sure it will help out a lot of users. Thank you for your contribution.

**Comment by steviehs** [comment]
That's good news! So I think I wait with touching each of my 360 folders :-)
I have another script - digiimport - which renames picts in an incoming folder to their timestamps and sorts them in a structured (YYYY/MM) folder hierarchy, this is still perl, I will migrate this to python and make it also public...

**Comment by steviehs** [comment]
https://gitlab.com/steviehs/stevemisc has now also the digiimport.py script.

**Comment by steviehs** [comment]
Hmm... I did not really find how to set all folders to local? Is the intention, that I "select all folders" and then "insert locally" (dunno how the english command is named)? If that is the way to go, then there is an issue with that, as "insert locally" is disabled when I select approx more than 10 folders...

**Comment by scubajeff** [comment]
That's the result of DeepL translation. So what is the correct way to say "Set Local"?

That menu item will be disabled if the selections contain mix of local and remote albums. I just tested it on my phone, I have about 30 albums, all remote, I select them all and the menu item is activate as it should be.

**Comment by steviehs** [comment]
hehe, no, it was my reverse translation from German. "Set Local" seems to be fine for me :-)
You are right, now this works, but I am lost as I have already 100+ Albums set locally and the rest is still remote. But if everything works right, I just could delete and reinstall lespas again. Still from the logical aspect I'd say if you select all folders and say "Set local" it just should ignore a folder which is already local... 

But a big thanks anyway! and: I love the Muzei Feature....

**Comment by scubajeff** [comment]
In order not to cluster the menu, there is only one menu item to toggle local/remote back and forth, so the selection has to be pure.

**Comment by steviehs** [comment]
> In order not to cluster the menu, there is only one menu item to toggle local/remote back and forth, so the selection has to be pure.

Ah, ok, got it. Anyways. It works fine to delete and install lespas to select from then all remote folders to be local. Just takes "a minute" :-)
