### ISSUE TITLE
Crash right after opening the app

### ISSUE THREAD

**Issue by raphaelporsche** [scubajeff/lespas#54]
Hello @scubajeff
I wanted to give lespas another try as it seems to have matured a lot. While it seems to work fine on my smartphone (Mi Note 10 Lite, Android 11, MIUI 12.5.7), it crashes just after opening the app on my wife's smartphone (POCO something, Android 11, MIUI Global 12.5.5, Lespas 2.5.5 from Google Play Store.).
There is no error message, the app is just closing. After that I uninstalled Lespas completely to remove any data and configuration and reinstalled it from Play store. Now, the Nextcloud login screen was shown and I could log in successfully. When the lespas main screen is shown after around half a second (probably right when the syncing should start), the app closes without an error.
No matter what I do, the app always quits in the main screen.

Do you have any ideas how I should continue debugging? Are there any logs I could look into?
Thank you for your amazing work!

**Comment by scubajeff** [comment]
i don't use firebase, so can't do much remotely in this situation. do u happen to have a Android Studio development environment, or anything like a log reader? if yes, you could connect your wife phone to it and there should be a crash log entry.

**Comment by scubajeff** [comment]
are you both accessing the same nextcloud folder? self-hosted or a managd instance? are you both using the user account? 

another user report the same situation like this. i make a debug version including some changes which seems fixed his problem. would you like to try out this fix?

**Comment by raphaelporsche** [comment]
yes, we are both accessing the same nextcloud server (self hosted, different users, each with own (empty) lespas folder which isn't shared. I would like to try out the debug version, thank you.

**Comment by scubajeff** [comment]
https://github.com/scubajeff/lespas/issues/45#issuecomment-1099272433

**Comment by raphaelporsche** [comment]
Sorry, the debug build doesn't solve the problem. After ~3 seconds lespas just quits without an error message.
I noticed something interesting though. If I click on the Plus symbol in these 3 seconds, lespas doesn't quit. I can select an image and add them to an album or even cancel the creation. In both cases les pas keeps running and doesn't quit. I can continue to use the app normally, photos are synchronized to nextcloud. If I quit lespas and restart it and wait 3 seconds, it will be closed again. Does this help in the debugging process?

**Comment by scubajeff** [comment]
so all these only happened in one of the two phones?

**Comment by raphaelporsche** [comment]
I was able to get some further inside into the problem.
- I switched nextcloud accounts (my phone with my wifes nextcloud account and her phone with mine). Turns out lespas is quitting on my phone, now!
- I continued with digging into the logs of my nginx reverse proxy:
Here is the log, when I start lespas with my own (non-crashing) nextcloud account:
 ```
nginx    | 192.168.0.122 - Raphael [16/Apr/2022:11:39:11 +0200] "PROPFIND /nextcloud/remote.php/dav/files/Raphael/lespas HTTP/2.0" 207 343 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Raphael [16/Apr/2022:11:39:11 +0200] "GET /nextcloud/ocs/v1.php/apps/files_sharing/api/v1/sharees?itemType=file&format=json HTTP/2.0" 200 393 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Raphael [16/Apr/2022:11:39:12 +0200] "PROPFIND /nextcloud/remote.php/dav/files/Raphael/lespas HTTP/2.0" 207 433 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Raphael [16/Apr/2022:11:39:12 +0200] "GET /nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares?path=lespas&subfiles=true&reshares=false&format=json HTTP/2.0" 200 81 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Raphael [16/Apr/2022:11:39:12 +0200] "GET /nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares?shared_with_me=true&format=json HTTP/2.0" 200 81 "-" "LesPas_v2.5.5" "-"
```

This is the log when my wife starts lespas
```
nginx    | 192.168.0.122 - Julia [16/Apr/2022:11:10:01 +0200] "PROPFIND /nextcloud/remote.php/dav/files/Julia/lespas HTTP/2.0" 207 341 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Julia [16/Apr/2022:11:10:01 +0200] "GET /nextcloud/ocs/v1.php/apps/files_sharing/api/v1/sharees?itemType=file&format=json HTTP/2.0" 200 395 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Julia [16/Apr/2022:11:10:02 +0200] "GET /nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares?path=lespas&subfiles=true&reshares=false&format=json HTTP/2.0" 200 81 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Julia [16/Apr/2022:11:10:02 +0200] "PROPFIND /nextcloud/remote.php/dav/files/Julia/lespas HTTP/2.0" 207 386 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Julia [16/Apr/2022:11:10:02 +0200] "GET /nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares?shared_with_me=true&format=json HTTP/2.0" 200 540 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Julia [16/Apr/2022:11:10:03 +0200] "PROPFIND /nextcloud/remote.php/dav/files/Julia HTTP/2.0" 207 784 "-" "LesPas_v2.5.5" "-"
```
There is an additional PROPFIND request on the Nextcloud root folder of hers. What is that for? This seems to crash lespas.
I have several other folders (e.g. documents) which are shared from my account to hers. Maybe this is the problem.

**Comment by scubajeff** [comment]
@raphaelporsche your finding is really helpful. since you didn't modify the 'share_folder' parameter in your Nextcloud config file, Nextcloud will put all user's share in user's root folder, LesPas uses that PROPFIND request to find out user's 'share_with_me' folders. Reading from the server log, that request returned successfully. But something went wrong in processing the response.

Could you please send me the result of the PROPFIND request? First create a text file `propfind.txt` with the following content:
```
<?xml version="1.0"?>
<d:propfind xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
 <d:prop>
  <oc:fileid/>
  <d:getcontenttype/>
  <d:getlastmodified/>
  <d:getetag/>
  <oc:share-types/>
  <d:getcontentlength/>
 </d:prop>
</d:propfind>
```
Then use the following command:
```
curl -u <userid>:<password> -X PROPFIND --data "@propfind.txt" 'https://<server>/nextcloud/remote.php/dav/files/Julia/'
```

If you feel uncomfortable pasting the result here, you can send them to my email: scubajeffrey@criptext.com

**Comment by raphaelporsche** [comment]
@scubajeff Ah I see, I created a new user Test, deleted all files, and added all the shares from my wife till lespas crashed. Turns out is is a music directory.

Here is the nginx log
```
nginx    | 192.168.0.122 - Test [16/Apr/2022:16:22:42 +0200] "PROPFIND /nextcloud/remote.php/dav/files/Test/lespas HTTP/2.0" 404 236 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Test [16/Apr/2022:16:22:42 +0200] "GET /nextcloud/ocs/v1.php/apps/files_sharing/api/v1/sharees?itemType=file&format=json HTTP/2.0" 200 417 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Test [16/Apr/2022:16:22:42 +0200] "GET /nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares?path=lespas&subfiles=true&reshares=false&format=json HTTP/2.0" 404 110 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Test [16/Apr/2022:16:22:42 +0200] "MKCOL /nextcloud/remote.php/dav/files/Test/lespas HTTP/2.0" 201 0 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Test [16/Apr/2022:16:22:43 +0200] "PROPFIND /nextcloud/remote.php/dav/files/Test/lespas HTTP/2.0" 207 341 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Test [16/Apr/2022:16:22:43 +0200] "GET /nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares?shared_with_me=true&format=json HTTP/2.0" 200 410 "-" "LesPas_v2.5.5" "-"
nginx    | 192.168.0.122 - Test [16/Apr/2022:16:22:43 +0200] "PROPFIND /nextcloud/remote.php/dav/files/Test HTTP/2.0" 207 426 "-" "LesPas_v2.5.5" "-"
```

Here is the PROPFIND request answer which crashes lespas:
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:"
    xmlns:s="http://sabredav.org/ns"
    xmlns:oc="http://owncloud.org/ns"
    xmlns:nc="http://nextcloud.org/ns">
    <d:response>
        <d:href>/nextcloud/remote.php/dav/files/Test/</d:href>
        <d:propstat>
            <d:prop>
                <oc:fileid>585222</oc:fileid>
                <d:getlastmodified>Sat, 16 Apr 2022 14:22:42 GMT</d:getlastmodified>
                <d:getetag>&quot;8faee301394c5c3fdb49c23b685f4ed1&quot;</d:getetag>
                <oc:share-types/>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
        <d:propstat>
            <d:prop>
                <d:getcontenttype/>
                <d:getcontentlength/>
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
    </d:response>
    <d:response>
        <d:href>/nextcloud/remote.php/dav/files/Test/lespas/</d:href>
        <d:propstat>
            <d:prop>
                <oc:fileid>585324</oc:fileid>
                <d:getlastmodified>Sat, 16 Apr 2022 14:22:42 GMT</d:getlastmodified>
                <d:getetag>&quot;625ad132c9203&quot;</d:getetag>
                <oc:share-types/>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
        <d:propstat>
            <d:prop>
                <d:getcontenttype/>
                <d:getcontentlength/>
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
    </d:response>
    <d:response>
        <d:href>/nextcloud/remote.php/dav/files/Test/Musik-Shared/</d:href>
        <d:propstat>
            <d:prop>
                <oc:fileid>71149</oc:fileid>
                <d:getetag>&quot;613a1c0996d47&quot;</d:getetag>
                <oc:share-types/>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
        <d:propstat>
            <d:prop>
                <d:getcontenttype/>
                <d:getlastmodified/>
                <d:getcontentlength/>
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>
```

Hope, this is usefull for you.

**Comment by scubajeff** [comment]
got it. lastmodified is missing.

**Comment by scubajeff** [comment]
Here is a new debug build, please give a try.
[LesPas-v2.5.5-debug.zip](https://github.com/scubajeff/lespas/files/8500167/LesPas-v2.5.5-debug.zip)

**Comment by scubajeff** [comment]
By the way, if you don't like Nextcloud populates received shares onto your home folder, please consider changing `share_folder` parameter in your Nextcloud config file.

**Comment by raphaelporsche** [comment]
Thank you very much, the debug build solves the problem, no more crashes 🥳

P.s. I am making heavily use of the folder sharing feature (documents, music, audiobooks, ...) and I want the shared folders to appear in the root folder. I am planning to share the whole lespas folder as we are creating family albums and everyone will be up to date automatically. A first test doing this went without problems just now 👍

**Comment by scubajeff** [comment]
I haven't test this use case of sharing the lespas/ folder. Feel a little bit nervous on how it goes. You can use LesPas' built in 'Publish' function to share the albums to particular user/group.
