### ISSUE TITLE
Mistake between Sync status and the reality.

### ISSUE THREAD

**Issue by ghicat** [scubajeff/lespas#55]
Hello @scubajeff ,

I see a difference between the lespas sync status and what I exactly have on my server.

This is the sync status
![Screenshot_20220417-233716.jpg](https://user-images.githubusercontent.com/26241858/163733039-52ad395d-6476-439b-9e4c-2bc0dcc41ed1.jpg)

Here is the gap in my nextcloud server
![Screenshot_20220417-233802.jpg](https://user-images.githubusercontent.com/26241858/163733130-8650ba28-e71c-4e12-a6a3-432516523b73.jpg)

And here is an example of photos present in my roll but not on the server
![Screenshot_20220417-234003.jpg](https://user-images.githubusercontent.com/26241858/163733217-780769c2-d725-4651-8514-07ccee231479.jpg)

I tested to stop and restart the syncing but no effect.

Thank you 😊

**Comment by scubajeff** [comment]
LesPas will backup photos in camera roll which date of taken is later than LesPas's install time. Try taking some new shots and see.

**Comment by ghicat** [comment]
Maybe it is preferable to sync all the folder untill the first element to be sure. I am not sure that everyone install LesPas app before taking their first photo.

**Comment by scubajeff** [comment]
i did spend sometime thinking about this when I started adding camera roll bckup feature. The reason why I settled on this way is that, first of all if user had taken a lot of photos before installing LesPas, it would take quite a while to do the backup, and secondly, most likely user will already had one way or another doing their backup, no need to create duplication.
