### ISSUE TITLE
Start camera roll in the image list. #FeatureRequest

### ISSUE THREAD

**Issue by raphaelporsche** [scubajeff/lespas#59]
If you are opening the camera roll, most of the time you don't want to view the last image, so it would be handy to start camera roll in the image list (appearing if you scroll up).

**Comment by scubajeff** [comment]
There is a setting for this.

**Comment by raphaelporsche** [comment]
Ah I didn't see the setting, thanks a lot that solves it.

**Comment by raphaelporsche** [comment]
Ah I didn't see the setting, thanks a lot that solves it.
