### ISSUE TITLE
Progress bar/upload indicator when adding image to remote albums. #FeatureRequest

### ISSUE THREAD

**Issue by raphaelporsche** [scubajeff/lespas#60]
When adding a lot of images to a remote album, there is no feedback when all the images are uploaded. It would be handy to have a little icon/progress bar on the album to show that uploading is in progress.

**Comment by scubajeff** [comment]
this has been asked before, and my answer is still no. the sync process has been proven to be solid. no need to worry about it.

**Comment by scubajeff** [comment]
I got your point and really appreciate all the efforts you have been putting on this app. 

I host my Nextcloud server on a Pi 3B and expose it to the internet, my parents live in another town from mine and access it through their DSL line. It has been more than a year now, and Les Pas never fail me or them. That's why I believe the sync works pretty solid as long as the network is stable. And by the way, The speed of the DSL line on both end are 100Mb/s, we don't have speed problem under daily use, althought it took several days, yes days, for my dad to upload all his camera roll.

There are many kinds of edge cases that could jeopardize the sync, the app just can't tell if it's a temparately glitch of the network or a permanent one like the extremely volatile case as server name changed. Showing some fail uploading messages to the user after every glitch that might very well be fixed in the next round of sync just couldn't help much to solve the actual problem but only brings up the unnecessary anxiesity.

However I could use that "Publication" action icon on the first page as an indicator for network status. In fact, I already use it that way, since my family members published some albums to me, the button will turns on everytime I open Les Pas. If that icon is gray out, I would know there is something wrong with the network. I should make it a little bit more exaggerated.

**Comment by raphaelporsche** [comment]
Thanks for your reply! I really think most photo apps concentrate on the completely wrong thinks like a fancy web gui without a mobile apps. My theory is, that most users want the basic stuff from an photo app: 1.) mobile and completely controllable by a mobile app 2.) photo syncing/saving in the background 3.) creating and sharing albums between family members and friends. Las pass fulfills all those points and I think it could be one of the most used self-hosted apps out there (just look how big all those google-photos-replacement-threads are). It is such a great software and it is nearly there.

Back to the status: What about putting an icon in the title bar beneath the circle:
1. ![icon_green_checkmark](https://user-images.githubusercontent.com/70773164/167258169-abc34908-2a8f-4609-8f91-2db844231101.png) green checkmark -> there is a connection and everything is in sync
2. ![icon_grey_checkmark](https://user-images.githubusercontent.com/70773164/167258208-80916800-4f17-47d1-b8b8-49ce3a79ea2a.png) grey checkmark -> currently no connection to nextcloud but last time we had a connection everything was in sync and there are no local chances since then
3. ![icon_grey_circle](https://user-images.githubusercontent.com/70773164/167258297-5d6c7a68-d322-4300-8d61-0637bd56fbba.png) green loading -> we have a connection and data is is beeing uploaded/downloaded
4. ![icon_greycircle](https://user-images.githubusercontent.com/70773164/167258317-90293331-e34e-42b3-9fbc-483d5a17b7df.png) grey loading -> we lost connection when there was still things to sync or in the meantime there were local changes
5.  
![icon_grey_x](https://user-images.githubusercontent.com/70773164/167258392-dc66cbbf-9f06-46ba-ba2a-34546cac2714.png) (optional) grey x -> there was some problem with nextcloud (e.g. wrong response, ...)

This would be very easy to understand for most of the users and at the same time give valuable information.

**Comment by scubajeff** [comment]
I have another idea regarding sync status. You see, there is already a status message for camera roll backup in the Setting menu. I could make another one for album sync in "Auto Sync" menu item summary.

I totally agree with you that an app centric solution is the future. Nowaday, people create and consume content all on their phones. Web browser on a desktop is just so 90's, Ordinary user won't even have PCs.

**Comment by raphaelporsche** [comment]
I see your point not to clutter the main screen. I agree, that putting the status message into the settings menu is a good alternative. Although I would recommend to put it to the top (into a new category) so that scrolling is not neccessary.

Another alternative is to create a new menu entry "Sync status" which opens another dialog. Maybe even name the menu item dynamically ("Syncing with 4mb/s...").

**Comment by scubajeff** [comment]
Don't get me wrong, data safety is very important. If my memory is correct, nearly all the quick fixes I released so far are somehow related to sync and backup. The priority is at the top of the list. However, this app is not a sync app, I would rather guiding user to put their eyes on enjoying and sharing their memories with their loved ones, than letting them worrying where the hell are their files at the very moment.

There is a long way to go to be absolute robust as Google vault can be, and probably never will, the one thing I'm sure is I will keep fixing them once those bugs arise, getting closer to that target on every move.

**Comment by raphaelporsche** [comment]
I strongly disagree. Since you are handling all syncing yourself instead of relying on e.g. the nextcloud app, syncing is the central element in lespas (otherwise it would be a local gallery app). Since there is no feedback about server connectivity, syncing status or error messages, I would not trust any data to les pas which I can't afford to loose. If you don't believe me start a survey how many users care about where their files are at the very moment. I bet nearly 100% of the selfhosted community cares.

To give you a positive example about communicating sync status to the user, I created a screenshot of immich which will be one of the main competitor of les pas:
![Screenshot_2022-05-09-12-52-34-323_app alextran immich](https://user-images.githubusercontent.com/70773164/167398673-a64a7110-23b4-4233-b6aa-30556e2a292f.jpg)

You could hide these information in a sub menu to not bother the users who don't care, but I think providing this information is essential for such kind of app.

**Comment by scubajeff** [comment]
Ok, let's agree on the disagree. A preference item will be implemented in Setting screen, showing how many sync actions (not just upload, but also copy, move, new album created etc.) are still undergoing, this could protentially be a signal to bring user's attention to some persistant issues that might preventing sync from finishing.

As for Immich, that's a self-contained integrated solution. Like a Photoprism, librephoto clone with fancy clients. I don't think Les Pas is a competitor to it. Only chance Les Pas has, is when user start to realise photo is not the only solution they need, there are calendar, contact, notes taking too. Then an AIO server backend is a better choice.

**Comment by scubajeff** [comment]
A sync status is added in release 2.5.10
