### ISSUE TITLE
Show memories #FeatureRequest

### ISSUE THREAD

**Issue by raphaelporsche** [scubajeff/lespas#63]
This idea is from my wife and I really liked it: Google photos randomly shows memories ("1,2,3,4,x years ago") as push up notifications. We really like this feature (showing e.g. old baby photos).
Les pas could select some photos randomly from the same date but x years ago and download them to a temporary album and show the temporary album in the notification screen. Googles photo selection is way more complex (see https://blog.google/products/photos/new-memories-features-look-back/) but randomly choosing photos from dates would be sufficient for the daily use.
What do you think?

**Comment by scubajeff** [comment]
It's already there, maybe not in a way you like. Les Pas can act as a image source to a brillian opensource wallpaper app [Muzei](https://f-droid.org/en/packages/net.nurik.roman.muzei/). Once your installed both, Les Pas can feed a "Today in history" stream right to your phone's desktop. Wallpaper might not be everyone's favorite, but I believe it's more a auto-pilot hand free mode comparing to openning Les Pas everyday just to see if there is a surprise.
