### ISSUE TITLE
Les Pas crashes right away (since 2.5.7)

### ISSUE THREAD

**Issue by p3titbo3uf** [scubajeff/lespas#64]
**Describe the bug**
After giving the authorization to Les Pas (v 2.5.7, 2.5.8 and 2.5.9) to access my Nextcloud (through an 2FA process), and grant the app authorization to to access my local data, the app crashes.

**Expected behavior**
Access my remote Les Pas folder.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: e OS Pie (android 9)

**Comment by scubajeff** [comment]
This seems to be related to the implementation of True Black theme. Reported from some old Xiaomi devices too. Do you know how to get a logcat output? That would help.

**Comment by p3titbo3uf** [comment]
Just tried to install the latest version of the app with my phone running on a light theme : same crash :(
Here is a logcat : [logcat.txt](https://github.com/scubajeff/lespas/files/8668635/logcat.txt).
You can see it I'm running successfully the 2.5.5 version of the app, no matter what theme I'm using.

**Comment by scubajeff** [comment]
thanks for reporting. this bugs is fixed, will be included in next release.

**Comment by p3titbo3uf** [comment]
You rock ! Thanks for the great work and for sharing it ;)
