### ISSUE TITLE
Let's encrypt sertificate

### ISSUE THREAD

**Issue by alex000090** [scubajeff/lespas#65]
Dear scubajeff,
Could you add the ability to trust the let's encrypt sertificate?

**Comment by scubajeff** [comment]
it's supported. i myself am using it right at this momemt. can you post a screenshot of where you got stuck?

**Comment by alex000090** [comment]
![Screenshot_20220511-170258](https://user-images.githubusercontent.com/1015002/167845446-25578623-8138-4615-8c53-a0b06bdbd81c.png)

I can't go next this step.

**Comment by scubajeff** [comment]
I can access your site using browser, but the command
```
curl -X GET 'https://bregz.sknt.ru/ocs/v2.php/cloud/capabilities?format=json' -H "OCS-APIRequest: true" 
```
prints the following error here:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
```
A search on this on DDG give me the [possible cause](https://stackoverflow.com/a/35869560).

**Comment by alex000090** [comment]
Dear scubajeff,
I am immensely grateful to you for the hint!
My mistake was in NGINX configuration file for nextcloud.
I have cert.pem for sertificate instead fullchain.pem.
Now all works!

**Comment by scubajeff** [comment]
@alex000090 if you happened to install Les Pas from Google Play, could you please leave your comment and rating there for it? many thanks.
