### ISSUE TITLE
Consumed all available data even with sync wifi only enabled

### ISSUE THREAD

**Issue by Gene-W** [scubajeff/lespas#7]
**Describe the bug**
I updated lespas yesterday and this morning I have zero data left on my mobile. I checked mobile data usage and there is one app displayed: lespas consumed all of my available data, nearly 5gb.

I checked lespas settings again: backup camera roll is off, sync periodically is off, update wifi only is on, yet somehow overnight it did something with nearly 5gb of data.

There actually should have been nothing to sync, I synced everything on wifi and haven't taken a photo in weeks.

**Expected behavior**
Any syncing should only take place while on wifi.

**Smartphone (please complete the following information):**
 - Device: Nokia
 - OS: Android 9

*Other related information *
I'm  reporting this as a bug to bring awareness but I am not willing to test further releases. I had just refilled my mobile data for the next month a few days ago and now have zero data left.

It's a very nice app, but I cannot afford to reload my data several times each month.

**Comment by scubajeff** [comment]
Very sorry to hear that. Is there a way I could redeem your lost?

**Comment by scubajeff** [comment]
Syncing started when Wifi is available won't stop when device leave Wifi network, will continue syncing in mobile network. Quick fix will come soon.
It's really a terrible feeling when you know other people lost money because of your fault.

**Comment by Gene-W** [comment]
Hey scubajeff, its really ok with me. I just wanted to be sure to share the issue before someone is affected in a worse way. I use open source as much as possible and I appreciate your hard work and the open source community. It's not going to be perfect every time, there are chances to take and that's ok too. Your app is quite useful and very attractive and very well done. Keep in mind that I install any app I use by my own choice so please don't worry about it and keep doing what you do, developing for the open source community!

**Comment by scubajeff** [comment]
Thank you very much for your kindness and your encouraging words. Yes, this is a serious bug, too much refectoring make that network type checking code to a wrong place.
