### ISSUE TITLE
Les Pas sync with LDAP authentication on Nextcloud server

### ISSUE THREAD

**Issue by noc0lour** [scubajeff/lespas#71]
**Describe the bug**
If LDAP for single-sign-on is used on the nextcloud server the login username and the URL to access folders of this user differ. After setup the Les Pas app tries to access `/dav/files/$username/lespas` instead of the actual basepath which looks more like `/dav/files/5e*******-*****-*****-9efe-b*****90fda/lespas`. I don't know exactly how the Nextcloud API works here. Maybe there is some return value you can use after login to get the basepath from the server?

With LDAP and other SSO methods even multiple different usernames are possible for the same user.

**Comment by scubajeff** [comment]
Thanks for reporting, I'll look into this. This is something new to me, might take a little bit of time.

**Comment by noc0lour** [comment]
Ah, I just read https://docs.nextcloud.com/server/stable/developer_manual/client_apis/LoginFlow/index.html#obtaining-the-login-credentials which is referenced in your source code. 

And here this is stated:

> loginname: The username that the client must use to login. Note: Keep in mind that this is the loginname > and could be different from the username. For example the email address could be used to login but not > for generating the webdav URL. You could fetch the actual username from the OCS API endpoint <server>/ocs/v1.php/cloud/user.

So I guess after login another call to get the username to this endpoint is necessary.

**Comment by scubajeff** [comment]
Thank you. Is it possible for you to test a debug build? I don't have a LDAP server.

**Comment by scubajeff** [comment]
@noc0lour please help testing this build

1. See if it fixes LDAP authentication
2. If it fixed, please test re-login function in Setting screen
3. If it fixed, please click logout function in Setting screen, see if your login name, rather than the encoded user_id is shown in the dialog

Many thanks. 

[LesPas-v2.5.10-debug-ldap.zip](https://github.com/scubajeff/lespas/files/8775766/LesPas-v2.5.10-debug-ldap.zip)

**Comment by scubajeff** [comment]
release 2.5.20 supports LDAP
