### ISSUE TITLE
Show scrollbar

### ISSUE THREAD

**Issue by steviehs** [scubajeff/lespas#75]
I really look forward to see the current version arriving in f-droid so I could test your addidtions ;-) Is there any other way to get hands faster on the apk except from compilng myself? :-)

As you already know, I have a really long (around 400) top level folders list sorted by YYYY_MM. One of my regular applications is, to search for something that happened 10 years ago and that means, I have to scroll down 120 folders. Would it be possible to switch on a scrollbar to scroll faster to folders?

Thx a lot for all your work! I will update my blockpost about organizing digipics soonish and refer to lespas as the only tool you need on an android device....

**Comment by steviehs** [comment]
Great thanks!

**Comment by scubajeff** [comment]
Are those device pads or phones?

**Comment by steviehs** [comment]
just checked on tablet, looks same there. It looks the same... but rather small... Is this the UI toolkits default or is there some chance to change?

**Comment by scubajeff** [comment]
Right now it's a fixed width for every screen size. It can be adjust to different screen size. Just need your real life experience on how wide it should be for each of the device you owned.

**Comment by steviehs** [comment]
is "double the actual size" precise enough? :-)

**Comment by scubajeff** [comment]
scrollbar thumb size fixed in release 2.5.16

**Comment by steviehs** [comment]
thanks! works better - at least for me :-)
