### ISSUE TITLE
misspelled word in pop up message

### ISSUE THREAD

**Issue by digitaldissent** [scubajeff/lespas#76]
When moving a photo from Camera Roll to an album where the photo already exists this message pops up.

![IMG_20220622_082705](https://user-images.githubusercontent.com/24197096/175071839-309e4f00-6456-4173-a0b7-f4a7b4fb501d.jpg)

Version 2.5.12 from FDroid

**Comment by scubajeff** [comment]
Thank you for reporting this.

**Comment by digitaldissent** [comment]
NP, I love the app thanks for putting your time into it.
