### ISSUE TITLE
Nothing in camera roll

### ISSUE THREAD

**Issue by guiyou65** [scubajeff/lespas#77]
**Describe the bug**
I took pictures with my camera and nothing appears in the camera roll  

**To Reproduce**
Steps to reproduce the behavior: take a picture and open Les Pas

**Expected behavior**
Unless I do not understand the App, I thought that every new picture will be present in the camera roll and so it is possible to organize album directly. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nokia 6.1
 - OS: LineageOs 19.1
 - Version Android 11

**Additional context**
I didn't find any tuto to help me on how it is supposed to work

**Comment by guiyou65** [comment]
I am using Lineageos, and in version 19.1, Android 11, and camera pictures are stored in the Pictures folder of main storage instead of DCIM folder. I noticed that Android 11 changed a lot of things with folders. Not always for the best even if it is for security matters.
But on my other device, still in Lineages 18.1, Android 10, although pictures are classically stored in DCIM, you can choose between main storage and sdcard.
Therefore it could be an idea to have a parameter to let the user choose the folder of pictures depending of the device/android version he uses.

**Comment by scubajeff** [comment]
I'm not aware that Google changes it's default camera saving folder to 'Pictures' officially in Android 12. As far as I know, camera output should be saved in DCIM folder, this is an industry standard. Altering this would break a lot apps.

As for the internal and external storage area differences, you don't have to worry, SAF will provide a unified image of all the files under the same folder name in both partitions.

**Comment by guiyou65** [comment]
Yes it works with DCIM folder on the external SDCard. And luckily I use Open Camera app that allows the choice of the storage folder wich is not DCIM by default. Even the out of the box LineageOS 19.1 camera application doesn't store pictures in DCIM any more. I read someting about security ...
However, it works nice now. Thanks a lot.
