### ISSUE TITLE
Allow servers with no cert

### ISSUE THREAD

**Issue by TheShanMan** [scubajeff/lespas#78]
I have an internal nextcloud server (not exposed to internet) and this app doesn't work because it gives a "site certificate error" with no way to proceed. Please add an option to ignore the lack of a cert. If nextcloud itself works just fine without a cert, why shouldn't Les Pas?

**Comment by scubajeff** [comment]
There is a section in README detailing how to make Les Pas working with self-signed certificate, it's a process proven by other users. Google Play market policy prevent app from ignoring self-signed cert. at runtime. Or am I reading it right? You are using unsafe http?

**Comment by TheShanMan** [comment]
I'm using https but haven't installed a cert and don't want to bother since the server isn't exposed. I installed both nextcloud and les pas from the fdroid store. Maybe that's why nextcloud has no problem with it? If they allow it for the fdroid version then maybe you could do the same if you think it's worthwhile. Otherwise I'm not really interested in setting up certs just to see if I like and want to use les pas. Either way, thanks for responding!

**Comment by scubajeff** [comment]
Maybe, I didn't dive into Nextcloud's code. I also believe that with an app as popular as it is, Nextclouder would have some privilage to settle exceptions with Google's policy reviewer. Anyway, I don't want the hassle of maintaining two code base, so thanks.

**Comment by felipegules** [comment]
Hello,
Same problem here, using the app from fdroid and would be cool to the app accept an insecure connection since it's pretty common use of a nextcloud that is not exposed to the internet and there's no need having a certificate.
Thanks the app looks very cool! It's very difficult and slow the native nextcloud app.

**Comment by scubajeff** [comment]
Les Pas support unsafe http connection to server, in login page, click the text of "https" will toggle http
