### ISSUE TITLE
LoginFlow for Android

### ISSUE THREAD

**Issue by sunjam** [scubajeff/lespas#8]
Hi, I was curious about [LoginFlow for Android](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/android_library/index.html), which uses the Nextcloud app on the phone in order to authenticate the user account.  This is an alternative to providing the URL and logging in.

Thanks either way for considering!

**Comment by scubajeff** [comment]
What Nextcloud file app does in the background is exactly what the other apps can do for themselve: request an app token by following Nextcloud's login flow. Frankly I don't see any advantage of going down this route. Please do enlighen me.

**Comment by Gajus84** [comment]
One advantage I could think of is the handling of Self-signed certificates which is already included in the Nextcloud App. I wasn't able to get Les Pas running if those are used.

**Comment by scubajeff** [comment]
right on time, buddy. the just released 1.4.4 gives you self-signed certificate support.

**Comment by sunjam** [comment]
The advantage of login flow is it pulls all the proper credentials and
server info from the Nextcloud app with one click.

1.  Click the SSO login button
2.  "Grant Access" (can also choose from multiple accounts if you have many
nextclouds)

So a greatly simplified process, similar to the flow you would expect from
Dropbox or Google when authorizing a third party app.  Hope this helps!

**Comment by scubajeff** [comment]
Yes, I read that document too. Considering not every nextcloud user has the File app installed, 3rd party apps have to deal with both situations. I opt for the plain old webview way because it works in all cases. Thought the user have to fill in server address and login credential one more time, a thing that I believe it's not much a burden.

**Comment by Rorschach1010** [comment]
+1 for SSO

It's not just that you have to fill in the address and credentials, some of us have activated 2FA in their nextcloud server so you have to create a new token for every site you want to give access to. Mix this with some users using custom roms and have to reset their phone sometimes, this because a process you want to be as quick as possible.

At the very least, it would be nice to be able to scan the qrcode, Nextcloud provides for every token but Singe-Sign-On with the NC app would obviously be better. Some Nextcloud android apps (like news or notes) let's you chose to use an account on the phone or simply login manually so maybe this is the best way, having both choices?

**Comment by scubajeff** [comment]
@Rorschach1010 well put. there seems to be more than a few ways to login, I have to go through them 1x1 before i can figure out the UX design.

**Comment by scubajeff** [comment]
seems like there is a Login Flow v2, will likely solve the problem i'm facing.

**Comment by scubajeff** [comment]
a special library from nextcloud is needed to use nc's sso which i'm not keen on to.

two ways left here:
continue using v1 login flow as it's right now, which give me total control of the process but leave out 2FA support, or

adapt to v2, which involves launching a browser app in the middle of the login process, a little bit odd, however much better support for 2FA and maybe future proved too.

**Comment by scubajeff** [comment]
a special library from nextcloud is needed to use nc's sso which i'm not keen on to.

two ways left here:
continue using v1 login flow as it's right now, which give me total control of the process but leave out 2FA support, or

adapt to v2, which involves launching a browser app in the middle of the login process, a little bit odd, however much better support for 2FA and maybe future proved too.

**Comment by Rorschach1010** [comment]
Ah, I see. v2 sounds good. I have seen quiet a few apps (android and desktop) going that way. some reddit apps for android for example. While this isn't what I hoped for, it would still be an improvement :D

**Comment by scubajeff** [comment]
I enable TOTP today on my server, I use andOTP to generate code on my phone,  I can login perfectly fine with no change to Les Pas's code.  What am I missing here? Are you guys using some other 2FA methods?

**Comment by Rorschach1010** [comment]
Ich think you misread my ealier post. 2fa is currently working with Les Pas, I'm using it myself. However, you have to always generate a new token whenever you have to reinstall the app. yYu can't copy it from your pc to your phone (well, there are tools for that) and it doesn't make sense to use keepass/bitwarden to save the token for the future.

Granted, for a normal user, you will configure Les Pas only once but for someone who often has to factory reset his phone, it is a hassle. Like I said, at the very least we should be able to scan the qrcode you get from the nextcloud server when creating a new token (you probably saw the code). the code includes the server url and the user credentials (name and token).

So yeah, it's to make things faster and easier, but it is working right now.

**Comment by scubajeff** [comment]
i see. is there a feature of nextcloud server that generates a login qr code?

**Comment by scubajeff** [comment]
found it. so a scanning app password qr code feature is what we need.

**Comment by Rorschach1010** [comment]
that would make things definitely quicker :D

**Comment by scubajeff** [comment]
yes. how could i not know this

**Comment by amo13** [comment]
Ah, too bad, I just found this discussion because I was hoping for the SSO login flow to come in a future update.

**Comment by scubajeff** [comment]
Apps use Nextcloud SSO will be forced to use Nextcloud's webdav library too, which means tremendous effort of refactoring Les Pas's network stack. Not possible in near future if not forever

**Comment by scubajeff** [comment]
Not gonna implement this
