### ISSUE TITLE
Exif orientation ignored?

### ISSUE THREAD

**Issue by steviehs** [scubajeff/lespas#80]
Could it be, that in one of the latest versions the Exif Orientation is ignored?  Version is 2.5.14

While it looks nice on my gnome nautilus: 

![grafik](https://user-images.githubusercontent.com/26877141/178231950-836d70d4-db61-4037-9b22-f8ef1e1f6723.png)

it is not looking nice in lespas:

![grafik](https://user-images.githubusercontent.com/26877141/178232456-de11bf5e-67ee-46cc-aa67-4ec91bc8ab04.png)

This is from the album overview, so it is not about the switch for turning the screen on/off. The issue persists in the picture view.

If I could do anything to help finding the bug, please let me know.

BTW: excuse me for always using sailing pictures as examples... I will go for cats in the next issues :-)

**Comment by scubajeff** [comment]
Is this picture in local or remote album? Does this happen to every portrait mode picture?

**Comment by steviehs** [comment]
The pictures are all in local album. I dunno when this started, I guess even with the very latest version, 2.5.14 as I was happy with 2.5.12 which was the first one to introduce to select all albums and set them remote. After that everything looked fine.

**Comment by scubajeff** [comment]
I can't reproduce this bug here. Is this the only picture that was affected by the bug? What if you delete and add it again?

**Comment by steviehs** [comment]
I have attached a picture which is shown in the wrong orientation. Basically all pictures which have a different Orientation than upper-left are shown wrong. 

![20220619_212009](https://user-images.githubusercontent.com/26877141/178528095-4a1aa8c1-62e2-4bbe-85b9-5f4f6f205bf0.jpg)

I just deleted it via lespas and added it again with my script. But as there is no force update, I have to wait some hours before it is checked again?

**Comment by scubajeff** [comment]
I re-produced it. It affects portrait mode pictures when they are added on server to a 'local' album. Fix is on the way.

**Comment by steviehs** [comment]
Great, thanks! This was not only portrait modes but also landscape pictures which had "upside down" EXIF orientation.

**Comment by steviehs** [comment]
Thanks for the fix, it works nice! I had to "resync" all my local pictures by setting all remote and then local again. Which takes over night... but it works!

**Comment by scubajeff** [comment]
Sorry for hassle. Next time when you need to update photo's metadata, you can use linux touch command on the affected photos and the folder too. Les Pas will kick off the rescan on next sync cycle. Should be more faster than downloading all files again.

**Comment by steviehs** [comment]
hmm... as there were for sure a few 100 if not 1000 of photos I would have had to write a script which checks for exif orientation and touches only this ones :-)
