### ISSUE TITLE
lespas does not recognize imported images

### ISSUE THREAD

**Issue by Happyfeet01** [scubajeff/lespas#82]
I have my complete collection of pictures, sorted into folders (YYYY/MM), imported to **DCIM/Pixel 6 pro**. This folder was created by Lespas during setup. 
But the images are not displayed in the Android app. Is there any way to get Lespas to recognize these images and videos?

**Comment by scubajeff** [comment]
I assume you only see a Camera Roll 'album' in your album list. You have to create your own albums. Just open the camera roll, swipe up to open the list view, then long press to select some photos, click the little 'footprint' icon and create your very first album.

Les Pas is **NOT** an auto categorizer, it organised your photos into folders/albums, therefore, you have to create them manually.
