### ISSUE TITLE
Sort order not stored persistent

### ISSUE THREAD

**Issue by steviehs** [scubajeff/lespas#83]
The sort order of the list of all albums is always "Descending Date" after I start lespas.
I change it from there to "Name descending" as this is my desired view.

And when I close lespas (by killing it from the apps list) and start it again, it is "Date Descending" again...

This does happen also on my tablets but - fun fact there - also the "real black baground" setting is not lost but after an app restart not applied again. So: switch is on "real black" but background is green. Switching off and on again fixes it.

**Comment by scubajeff** [comment]
Yes, the sorting order of album list is intended to be session based with the assumption that it works as a tool to find the particular album. I will try to make it persistent.
I also experienced the black theme issue once a while, only in android emulator, not in any of my phones though. Don't know exactly what went wrong yet. The theming code base is kind of messy.

**Comment by steviehs** [comment]
Thanks. The main reason is, that the albums are not generated in a timely manner... and file and directory dates tend go change when you copy. I could try to let my script touch the albums in a timely order. But I'd say storing the order settings is the better way to go.
