### ISSUE TITLE
Force camera roll sync

### ISSUE THREAD

**Issue by lgwapnitsky** [scubajeff/lespas#85]
Is it possible to force a sync of the whole camera roll?

**Comment by scubajeff** [comment]
Les Pas is a late comer and assums that user already has one way or another to back things up. When you switch on the backup setting, it will start backing up new photos.

**Comment by lgwapnitsky** [comment]
Ok, understood. I have 4 items.waiting to sync, and it's been that way for days. How do i figure out which ones and force it?

**Comment by scubajeff** [comment]
1. There are two different kind of messages shown in Setting's Sync section, one for camera roll backup statue and one for album sync statue, which one do you see the waiting message you mentioned?
2. Check your network connection, Les Pas default to sync only on WiFi
3. Did Les Pas prompt at startup that your internal storage is getting low? If yes, that will stop syncing.
4. You can go to Les Pas's camera roll management screen, there you will be able to see the camera roll on device, and the backup/archive on server, from that page, you will get the idea of which particular photos that got stuck in the queue

**Comment by lgwapnitsky** [comment]
1 - both
2 - done
3 - no
4 - error shows when I click the backup button

FYI, dcim folder is not being created, nor am i seeing existing albums in
Led Pas folder on NC

**Comment by scubajeff** [comment]
Are you using LDAP? or any other similar authentication layer?

**Comment by lgwapnitsky** [comment]
Yes

**Comment by scubajeff** [comment]
Great!
There is another user reported the same issue https://github.com/scubajeff/lespas/issues/71
I had made a debug version which hopfully fixes this. But unfortunately the guy reporting the bug seems to be busy and never feed back. Could you please give that debug version a try?

**Comment by lgwapnitsky** [comment]
Still not syncing. I have a video of my screen that i can send to you to
show what's going on

*Larry G. Wapnitsky*


*E: ***@***.****
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by scubajeff** [comment]
What authentication layer are you using? LDAP? 
The reason why lespas/ folder is not created on server is explained in #71. I believe the right way to nail this one is finding out the correct user name generated by the particular authentication layer, since all webdav file access to NC server use that name as the name of user's home folder.

**Comment by lgwapnitsky** [comment]
LDAP. I'll verify the username UID.

*Larry G. Wapnitsky*


*E: ***@***.****
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by scubajeff** [comment]
As discussed in #71, when you are using ldap, instead of your login name, nextcloud server will use a special id as your home folder name. That debug build in #71 has adapted to this behavior (I should have done this at the very beginning). But your test tells that it's still not working as expected. I need to forge another one which will print out what it got from nextcloud's get username api. I'm stuck with some other things right now. So hold on for a few days and I have the feeling we are very close to nail this one.

**Comment by lgwapnitsky** [comment]
no rush. Really appreciate it.

**Comment by scubajeff** [comment]
@lgwapnitsky Could you please help by doing the following:

1. Login to your server using ssh, find out the name of your account's data folder, e.g. the subfolder which holds your files under nextcloud data folder, usually is .../nextcloud/data/***
2. Find out which JSON name contain the same folder name in the output of the following command:
`curl -X GET 'https://server_address/ocs/v1.php/cloud/user?format=json' -H "OCS-APIRequest: true" -u your_acct_name:your_acct_password`

**Comment by lgwapnitsky** [comment]
{"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":{"enabled":true,"storageLocation":"\/var\/www\/nextcloud\/data\/7094395e-2b52-103b-96be-91ddb9ee6866","id":"7094395e-2b52-103b-96be-91ddb9ee6866","lastLogin":1661252794000,"backend":"LDAP","subadmin":[],"quota":{"free":52155486208,"used":54061666130,"total":106217152338,"relative":50.9,"quota":-3},"avatarScope":"v2-federated","email":"
***@***.***","emailScope":"v2-federated","additional_mail":[],"additional_mailScope":[],"displaynameScope":"v2-federated","phone":"","phoneScope":"v2-local","address":"","addressScope":"v2-local","website":"","websiteScope":"v2-local","twitter":"","twitterScope":"v2-local","organisation":"","organisationScope":"v2-local","role":"","roleScope":"v2-local","headline":"","headlineScope":"v2-local","biography":"","biographyScope":"v2-local","profile_enabled":"1","profile_enabledScope":"v2-local","groups":["admin","wappve","pfsense","ns-pgpool","ns-witness","anonaddy","mmnas","admins"],"language":"en","locale":"","notify_email":null,"backendCapabilities":{"setDisplayName":false,"setPassword":false},"display-name":"Larry
G. Wapnitsky"}}}

**Comment by scubajeff** [comment]
could you please verify that `/var/www/nextcloud/data/7094395e-2b52-103b-96be-91ddb9ee6866` is the folder that holds your account's files?

**Comment by lgwapnitsky** [comment]
It is

**Comment by scubajeff** [comment]
[LesPas-v2.5.17-debug.zip](https://github.com/scubajeff/lespas/files/9403083/LesPas-v2.5.17-debug.zip)
Ok, uninstall your current version, install attached debug version and try again please.

**Comment by lgwapnitsky** [comment]
I've been dealing with some personal stuff.  Will try asap

**Comment by lgwapnitsky** [comment]
No dice. Been waiting to sync since last night

**Comment by scubajeff** [comment]
Could you please send me the output of: `grep LesPas /var/log/apache2/access.log`

**Comment by lgwapnitsky** [comment]
I'm running NC on NGINX.  Is there something I can parse out of the logs
specifically?

**Comment by scubajeff** [comment]
Lespas use it's own user agent string when accessing the server. Just kill lespas app, restart it,  back to your server console, grep 'LesPas' in  your web server's access log then post the result here.

**Comment by Ronny-N** [comment]
Hi all
I had the same issue as I am using Nextcloud on a Nethserver instance (which uses LDAP for authentication). 
I have tried your version mentioned above (https://github.com/scubajeff/lespas/issues/85#issuecomment-1224113464) and can confirm it is working now. The DCIM folder has now been created and a new photo just got uploaded.

**Comment by scubajeff** [comment]
@Ronny-N Great! Could you please confirm if albums got synced to lespas/ folder on server too?

**Comment by Ronny-N** [comment]
> @Ronny-N Great! Could you please confirm if albums got synced to lespas/ folder on server too?

No, this did not work. No album folder has been created. I tried to add a photo to a new album, neither copy nor moving created a folder on my Nextcloud instance

**Comment by scubajeff** [comment]
@Ronny-N 
That's weird! Is there a lespas/ folder in your server's home?

**Comment by Ronny-N** [comment]
@scubajeff 
Sorry, I was looking at the DCIM folder. The album folders have been created under the lespas folder but they are empty. Also no albums show up on the les pas apps overview page

**Comment by scubajeff** [comment]
@Ronny-N Please try creating an album in the app and see if it sync.

**Comment by Ronny-N** [comment]
I tried again creating an album in the app. Now everything did work as expected.
However, I added a photo to a new album as mentioned before but now it worked

**Comment by scubajeff** [comment]
@Ronny-N
Nextcloud does not have server push ability right now, the syncing depends totally on the client client side, so either open Les Pas app (it will sync once upon launched) or let it auto-sync in 6 hour interval. I'm cooking a new version right now, it will give user more visual updates on what Les Pas is doing in the background to keep things synchronized.

**Comment by scubajeff** [comment]
@Ronny-N 
Sorry, I have some difficulties understanding your last message. Is everything working for you right now?

**Comment by Ronny-N** [comment]
@scubajeff Yes, now everything is working.

Just for clarification:
What I was trying to tell you is the first time adding a new album with the app did not work.
Furthermore, I never added an album folder on Nextcloud and also I do no expect server side manipulations get pushed back to the app. 

Thank you for all your effort in making and maintaining this app.

**Comment by scubajeff** [comment]
@Ronny-N Thank you very much for testing this debug built. Will conclude it after @lgwapnitsky reports back the result.

**Comment by Nitrousoxide** [comment]
It is also not backing up the photos for me either.  I tried your debug version and no beans, though it does sucessfully create albums and will properly copy/move photos to them, it doesn't create a DCIM folder nor does it back the camera roll.  From my logs it looks like it's running the correct dav command so I dunno.  I see it's TRYING to do stuff to DCIM, but the directory does not exist in the webgui for nextcloud, and ssh'ing into the underlying server doesn't show the directory there in the user directory either so I'm confident it doesn't exist.

172.70.110.232 - Brian [04/Sep/2022:16:21:17 +0000] "PROPFIND /remote.php/dav/files/Brian/lespas HTTP/1.1" 207 2034 "-" "LesPas_v2.5.17"
172.70.110.232 - Brian [04/Sep/2022:16:21:17 +0000] "PROPFIND /remote.php/dav/files/Brian/DCIM HTTP/1.1" 404 1713 "-" "LesPas_v2.5.17"
172.70.230.124 - Brian [04/Sep/2022:16:21:17 +0000] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=lespas&subfiles=true&reshares=false&format=json HTTP/1.1" 200 1609 "-" "LesPas_v2.5.17"
172.70.230.124 - Brian [04/Sep/2022:16:21:17 +0000] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?shared_with_me=true&format=json HTTP/1.1" 200 1601 "-" "LesPas_v2.5.17"
172.70.110.232 - Brian [04/Sep/2022:16:21:17 +0000] "MKCOL /remote.php/dav/files/Brian/DCIM HTTP/1.1" 423 1509 "-" "LesPas_v2.5.17"
172.70.230.18 - Brian [04/Sep/2022:16:20:10 +0000] "PROPFIND /remote.php/dav/files/Brian/lespas HTTP/1.1" 207 1909 "-" "LesPas_v2.5.17"
172.70.230.18 - Brian [04/Sep/2022:16:20:11 +0000] "DELETE /remote.php/dav/files/Brian/lespas/Home HTTP/1.1" 204 1303 "-" "LesPas_v2.5.17"
172.70.230.18 - Brian [04/Sep/2022:16:20:11 +0000] "PROPFIND /remote.php/dav/files/Brian/lespas HTTP/1.1" 207 2024 "-" "LesPas_v2.5.17"
172.70.230.18 - Brian [04/Sep/2022:16:20:11 +0000] "PROPFIND /remote.php/dav/files/Brian/DCIM HTTP/1.1" 404 1707 "-" "LesPas_v2.5.17"
172.70.230.18 - Brian [04/Sep/2022:16:20:11 +0000] "MKCOL /remote.php/dav/files/Brian/DCIM HTTP/1.1" 423 1513 "-" "LesPas_v2.5.17"

**Comment by scubajeff** [comment]
@Nitrousoxide I observed some strange things in the log, seems like you have multiple LesPas clients accessing the same account at the same time, they are from ip address: 172.70.110.232, 172.70.230.18, 172.70.230.124. When LesPas tried to create DCIM folder, server responded with code 423 which means resource locked, usually because the last access to it being interrupted.

**Comment by scubajeff** [comment]
@Nitrousoxide Although the camera backup doesn't seems to work so far, lespas/ folder is created successfully, that confirms the authentication patch in this debug release worked as planned.

**Comment by Nitrousoxide** [comment]
@raphaelporsche I was noticing some file lock issues too so I installed and configured Redis as the nextcloud file cache and that seems to have fixed it. I did some more experiments with Les Pas after (aka a few minutes ago) and still cannot get it to backup the photo roll. I can successfully delete the DCIM directory from the nextcloud web client which from the server logs looks like it is making DAV calls like your app so I don't think the server lock issue remains. Lespas does successfully recreate DCIM after I delete it as well as oneplus_in2025 under it but then does nothing. I tried manually copying some photos into DCIM/oneplus_in2025/2020/01 from elsewhere in nextcloud which I believe is the directory syntax lespas would normally use and it can see and interact with those files just fine.  it could delete them with no file locks. still no backups made.

**Comment by scubajeff** [comment]
@Nitrousoxide 
Let's do these:

1. Launch Les Pas, go to setting, disable then enable Camera Roll backup option
2. Force quit Les Pas from your system setting
3. Shoot some photos
4. Launch Les Pas again, create a new album by clicking the "Plus" button
5. Wait for a minute or two
6. Goto your server, see if new album is created under lespas/ folder, and if photos shot at step 3 is in a sub-folder name after your device in DCIM/

**Comment by scubajeff** [comment]
@Nitrousoxide That's by design. Les Pas assumes user already has some other working backup solutions.It will not upload those pictures shot before it's installation.

**Comment by Nitrousoxide** [comment]
Hmm, seems to me you probably either want to document that in the readme or in a popup when you select to backup (since I certainly expected that behavior) or on first run and setup have it backup the existing roll.

**Comment by scubajeff** [comment]
I should probably come out of the shadow of acting like an late comer, as Les Pas maturing, user would expect it to be a Swiss Army knife kind of tool when dealing with photos. Adding an option to backup all or even simply set it as the default behavior would be the more appropriate way now. But first, I need to sort out solutions for some extreme cases like user might already have thousands of photos which would take hours of uploading. 

Thank you very much for time and suggestion!

**Comment by scubajeff** [comment]
release 2.5.20 supports LDAP, and also provides choice to backup existing pictures in camera roll for new installations.
