### ISSUE TITLE
On Android 12, how do you get your camera pictures into lespas?

### ISSUE THREAD

**Issue by BettaGeorge** [scubajeff/lespas#92]
I am not sure whether this is a bug report or whether I am using something wrong. Feel free to add a label.

Previously, I think lespas detected my phone's DCIM folder and showed me the photos therein so I could sort them into albums.

Now on Android 12 (more precisely, LineageOS 19), when I take a picture with my camera, it gets saved in Android's DCIM folder, but does not show in lespas. As a workaround, I can set Nextcloud's "Instant Upload" feature to monitor my DCIM folder and move its contents into a lespas album, but that means that new pictures only show up in lespas after six hours, which is ... less than ideal.

Did I overlook a setting, or did the new privacy enforcement of Android 12 break this feature?

**Comment by scubajeff** [comment]
> it gets saved in Android's DCIM folder, but does not show in lespas
what do you see in lespas's camera roll album? empty?

**Comment by BettaGeorge** [comment]
Correct, the camera roll is always empty for me now.

**Comment by scubajeff** [comment]
Did you do a complete upgrade with all the system being wiped out and all app re-install or an over the air upgrade?

**Comment by BettaGeorge** [comment]
Yes, fair enough. A fresh install has solved the problem, so it was probably some Android thing. Thank you!
